Repository openshift/enhancements, pull requests merged in 2019-09, with the labels that each got.

#3 enhancements/template: Drop 'enhancement(s)-' prefix
  enhancements/README.md
  enhancements/template.md
Labels: approved, lgtm, size/XS

#7 add must-gather current state
  must-gather.md
Labels: approved, lgtm, size/L

#5 Windows Containers productization design
  windows-containers/productization.md
Labels: approved, lgtm, size/L

#18 formalize what a must-gather image includes
  must-gather.md
Labels: approved, lgtm, size/XS

#30 ovn-kubernetes-ga
  enhancements/20190919-OVN-Kubernetes.md
Labels: approved, lgtm, size/L

#11 Add machine-instance-lifecycle proposal
  enhancements/machine-instance-lifecycle.md
Labels: approved, lgtm, size/L

#10 Windows node logging
  windows-containers/cluster-logging-windows-worker-nodes.md
Labels: approved, lgtm, size/L

#15 Automated Policy-based Disk Encryption on Boot Images
  enhancements/automated-policy-based-disencryption.md
Labels: approved, lgtm, size/XL

#34 samples on non-x86 proposal
  multi-arch/samples.md
Labels: approved, lgtm, size/L

#26 enhancement: user workload monitoring
  enhancements/user-monitoring-deployment.png
  enhancements/user-monitoring-request.png
  enhancements/user-namespaces-custom-resources.png
  enhancements/user-workload-monitoring.md
Labels: approved, lgtm, size/L

#44 Enhancements also facilitate public feature roadmap
  README.md
Labels: approved, lgtm, size/S

#41 Centralize operator manifest generation
  enhancements/centralized-manifest-openapi-generation.md
Labels: approved, lgtm, size/L

#21 add design for TLS config
  kube-apiserver/tls-config.md
Labels: approved, lgtm, size/L

#12 Add phone home support proposal
  enhancements/olm/phone-home-support.md
Labels: approved, lgtm, size/L

#33 add open questions to the template
  enhancements/template.md
Labels: approved, lgtm, size/XS

#40 inspect container endpoints collection
  enhancements/oc/inspect.md
  must-gather.md
Labels: approved, lgtm, size/L

#51 start a document about kube-apiserver certs
  enhancements/kube-apiserver/certificates.md
Labels: approved, lgtm, size/L

#4 add Precision Time Protocol support
  time/ptp.md
Labels: approved, lgtm, size/L

#14 storage-migration-for-etcd-encryption proposal
  enhancements/etcd/storage-migration-for-etcd-encryption.md
Labels: approved, lgtm, size/L

#32 Encrypting Data at Datastore Layer
  apiserver/encrypting-data-at-datastore-layer.md
Labels: approved, lgtm, size/L

#17 Prepare for Service Catalog & Broker Removal
  enhancements/service-catalog/prepare-service-catalog-and-brokers-for-removal.md
Labels: approved, lgtm, size/L

#54 Remove James Russell (coverprice) from OWNERS
  OWNERS
Labels: approved, size/XS
