Repository openshift/enhancements, pull requests merged in 2019-12, with the labels that each got.

#135 Add fall-back to must-gather.
  enhancements/must-gather.md
Labels: approved, lgtm, size/XS

#99 IngressController NodePort publishing strategy
  enhancements/network/ingress-nodeport-publishing.md
Labels: approved, lgtm, size/L

#110 installer: user provided subnets for GCP cluster
  enhancements/installer/gcp-customer-provided-subnets.md
Labels: approved, lgtm, size/L

#132 Various patches for the diskencryption enhancement
  enhancements/automated-policy-based-disk-encryption.md
Labels: approved, lgtm, size/M

#140 disk-encryption: Update to note we're not encrypting by default
  enhancements/automated-policy-based-disk-encryption.md
Labels: approved, lgtm, size/M

#23 Add the OpenStack UPI enhancement proposal
  enhancements/installer/openstack-upi.md
Labels: approved, lgtm, size/L

#119 Add baremetal provisioning configuration to a new CR
  enhancements/baremetal/baremetal-provisioning-config.md
Labels: approved, lgtm, size/L

#129 Manila CSI driver integration
  enhancements/storage/manila-csi-driver-operator.md
Labels: approved, lgtm, size/L

#108 LOG-545: Cluster logging Elasticsearch rollover data design
  enhancements/cluster-logging/cluster-logging-es-rollover-data-design.md
Labels: approved, lgtm, size/L

#43 Add proposal for Route Admission Policy
  enhancements/openshift-route-admission-policy.md
Labels: approved, lgtm, size/L

#143 Update snapshot enhancement for Kubernetes 1.17
  enhancements/storage/csi-snapshot.md
Labels: approved, lgtm, size/M

#151 updates to oc/update-kube-oc-bump doc
  enhancements/oc/upgrade_kubernetes.md
Labels: approved, lgtm, size/M

#155 route-admission-policy: update API to incorporate feedback
  enhancements/openshift-route-admission-policy.md
Labels: approved, lgtm, size/M

#126 Add default-ingress-cert ConfigMap enhancement
  enhancements/network/default-ingress-cert-configmap.md
Labels: approved, lgtm, size/L

#144 monitoring: tenancy alerting
  enhancements/monitoring/user-monitoring-deployment.png
  enhancements/monitoring/user-monitoring-rbac.png
  enhancements/monitoring/user-workload-monitoring.md
Labels: approved, lgtm, size/L

#152 Allow olm managed operators to expose metrics to the cluster monitoring
  enhancements/olm/olm-managed-operator-metrics.md
Labels: approved, lgtm, size/L

#158 Service Catalog and Broker Removal
  enhancements/service-catalog/service-catalog-and-broker-removal.md
Labels: approved, lgtm, size/L

#167 go mod tidy before vendor
  enhancements/oc/upgrade_kubernetes.md
Labels: approved, lgtm, size/XS
