Repository openshift/enhancements, pull requests merged in 2019-11, with the labels that each got.

#68 Updates dns plugin enhancement
  enhancements/dns/plugins.md
Labels: approved, lgtm, size/L

#91 Add compliance operator enhancement proposal
  enhancements/compliance-operator.md
Labels: approved, lgtm, size/L

#101 Add machine health check diagram
  enhancements/machine-api/machine-health-checking.md
  enhancements/machine-api/mhc.plantuml
  enhancements/machine-api/mhc.png
  enhancements/machine-api/mhc.svg
Labels: approved, lgtm, size/M

#79 Add Enhancement for node file integrity monitoring
  enhancements/security/file-integrity-operator.md
Labels: approved, lgtm, size/L

#103 installer: user provided subnets for AWS cluster
  enhancements/installer/aws-customer-provided-subnets.md
Labels: approved, lgtm, size/L

#105 installer: internal private-only AWS OpenShift clusters
  enhancements/installer/aws-internal-clusters.md
Labels: approved, lgtm, size/L

#96 enhancements/proxy/global-cluster-egress-proxy:
  enhancements/proxy/global-cluster-egress-proxy.md
Labels: approved, lgtm, size/L

#106 fix typo
  enhancements/proxy/global-cluster-egress-proxy.md
Labels: approved, lgtm, size/XS

#111 enhancements: Standardize YAML vs. header title syntax
  enhancements/automated-policy-based-disencryption.md
  enhancements/automated-service-ca-rotation.md
  enhancements/compact-clusters.md
  enhancements/compliance-operator.md
  enhancements/installer/aws-customer-provided-subnets.md
  enhancements/installer/aws-internal-clusters.md
  enhancements/kube-apiserver/certificates.md
  enhancements/kube-apiserver/encrypting-data-at-datastore-layer.md
  enhancements/kube-apiserver/tls-config.md
  enhancements/machine-api/machine-instance-lifecycle.md
  enhancements/mco-kargs-day1-support.md
  enhancements/multi-arch/samples.md
  enhancements/must-gather.md
  enhancements/network/20190903-SRIOV-GA.md
  enhancements/network/allow-external-ip-overrides.md
  enhancements/oc/olm-mirroring.md
  enhancements/oc/upgrade_kubernetes.md
  enhancements/ptp-time-integration.md
  enhancements/security/file-integrity-operator.md
  enhancements/service-catalog/prepare-service-catalog-and-brokers-for-removal.md
  enhancements/storage/csi-cloning.md
  enhancements/storage/csi-resize.md
  enhancements/storage/csi-snapshot.md
  enhancements/template.md
  enhancements/windows-containers/cluster-logging-windows-worker-nodes.md
Labels: approved, lgtm, size/M

#77 must-gather|oc/inspect: Fix YAML front-matter formatting
  enhancements/must-gather.md
  enhancements/oc/inspect.md
Labels: approved, lgtm, size/M

#116 enhancements/template: Fix openshift-docs links
  enhancements/automated-policy-based-disencryption.md
  enhancements/automated-service-ca-rotation.md
  enhancements/cluster-logging/cluster-logging-elasticsearch-proxy.md
  enhancements/cluster-logging/cluster-logging-log-forwarding.md
  enhancements/compact-clusters.md
  enhancements/compliance-operator.md
  enhancements/dns/plugins.md
  enhancements/etcd/storage-migration-for-etcd-encryption.md
  enhancements/installer/aws-customer-provided-subnets.md
  enhancements/installer/aws-internal-clusters.md
  enhancements/kube-apiserver/auto-cert-recovery.md
  enhancements/kube-apiserver/certificates.md
  enhancements/kube-apiserver/encrypting-data-at-datastore-layer.md
  enhancements/kube-apiserver/tls-config.md
  enhancements/mco-kargs-day1-support.md
  enhancements/monitoring/user-workload-monitoring.md
  enhancements/multi-arch/samples.md
  enhancements/must-gather.md
  enhancements/network/20190903-SRIOV-GA.md
  enhancements/network/20190919-OVN-Kubernetes.md
  enhancements/network/allow-external-ip-overrides.md
  enhancements/oc/inspect.md
  enhancements/oc/olm-mirroring.md
  enhancements/olm/operator-bundle.md
  enhancements/olm/operator-registry.md
  enhancements/olm/phone-home-support.md
  enhancements/olm/simplify-apis.md
  enhancements/proxy/global-cluster-egress-proxy.md
  enhancements/ptp-time-integration.md
  enhancements/security/file-integrity-operator.md
  enhancements/service-catalog/prepare-service-catalog-and-brokers-for-removal.md
  enhancements/storage/csi-cloning.md
  enhancements/storage/csi-resize.md
  enhancements/storage/csi-snapshot.md
  enhancements/template.md
  enhancements/user-defined-default-ingress-controller.md
  enhancements/windows-containers/cluster-logging-windows-worker-nodes.md
  enhancements/windows-containers/productization.md
  image-registry/automate-pruning.md
  image-registry/remove-registry-baremetal.md
Labels: approved, lgtm, size/M

#118 cleanup misplaced enhancements
  enhancements/image-registry/automate-pruning.md
  enhancements/image-registry/remove-registry-baremetal.md
Labels: approved, lgtm, size/XS

#120 Create Installer enhancement for GCP private/internal clusters.
  enhancements/installer/gcp-private-clusters.md
Labels: approved, lgtm, size/L

#121 Azure: Customer provisioned virtual network & subnets enhancement doc
  enhancements/installer/azure-bring-your-own-vnet.md
Labels: approved, lgtm, size/L

#122 Azure: Internal/Private clusters enhancement doc
  enhancements/installer/azure-private-internal-clusters.md
Labels: approved, lgtm, size/L

#125 Fix typo in "disk encryption" enhancement
  enhancements/automated-policy-based-disk-encryption.md
Labels: approved, lgtm, size/XS

#131 etcd-encryption: update for backup/restore
  enhancements/kube-apiserver/encrypting-data-at-datastore-layer.md
Labels: approved, lgtm, size/M
