Repository openshift/enhancements, pull requests merged in 2019-10, with the labels that each got.

#55 inspect: add pprof data collection
  enhancements/oc/inspect.md
Labels: approved, lgtm, size/XS

#35 Add CSI Cloning enhancement.
  storage/csi-cloning.md
Labels: approved, lgtm, size/L

#36 Add CSI Snapshot support.
  storage/csi-snapshot.md
Labels: approved, lgtm, size/L

#38 Add CSI resize enhancement
  enhancements/storage/csi-resize.md
Labels: approved, lgtm, size/M

#6 add SR-IOV GA proposal
  enhancements/20190903-SRIOV-GA.md
Labels: approved, lgtm, size/L

#9 Add machine-health-checking proposal
  enhancements/machine-health-checking.md
Labels: approved, lgtm, size/L

#39 make accept generic .status.relatedResources
  enhancements/oc/inspect.md
Labels: approved, lgtm, size/M

#58 Fix typos
  enhancements/oc/inspect.md
Labels: approved, lgtm, size/S

#59 update non-x86 samples EP to discuss CI
  enhancements/multi-arch/samples.md
Labels: approved, lgtm, size/XS

#29 cluster logging elasticsearch-proxy
  enhancements/cluster-logging/cluster-logging-elasticsearch-proxy.md
  enhancements/cluster-logging/images/elasticsearch-proxy.png
Labels: approved, lgtm, size/L

#28 Simplify OLM APIs
  enhancements/olm/simplify-apis.md
Labels: approved, lgtm, size/XL

#24 Enhancement for operator-registry
  olm/operator-registry.md
Labels: approved, lgtm, size/L

#62 Move olm registry enhancement to correct folder
  enhancements/olm/operator-registry.md
Labels: approved, lgtm, size/XS

#31 proposal: User-defined Default Ingress Controller
  enhancements/user-defined-default-ingress-controller.md
Labels: approved, lgtm, size/L

#42 Proposal for allowing RBAC based over-ride of external IPs
  enhancements/network/allow-external-ip-overrides.md
Labels: approved, lgtm, size/L

#50 add --size to inspect
  enhancements/oc/inspect.md
Labels: approved, lgtm, size/S

#66 monitoring: Update user workloads proposal
  enhancements/monitoring/user-monitoring-deployment.png
  enhancements/monitoring/user-monitoring-request.png
  enhancements/monitoring/user-namespaces-custom-resources.png
  enhancements/monitoring/user-workload-monitoring.md
Labels: approved, lgtm, size/M

#53 Configurable CoreDNS Plugins
  enhancements/dns/plugins.md
Labels: approved, lgtm, size/L

#27 Propose convention for storing operator bundle
  olm/operator-bundle.md
Labels: approved, lgtm, size/L

#65 Add upgrade kubernetes procedure for oc
  enhancements/oc/upgrade_kubernetes.md
Labels: approved, lgtm, size/M

#52 Common README information
  enhancements/operator-dev-doc.md
Labels: approved, lgtm, size/L

#16 cluster logging log forwarding proposal
  enhancements/cluster-logging/cluster-logging-log-forwarding.md
  enhancements/cluster-logging/images/log-forwarding-message-flow.png
Labels: approved, lgtm, size/L

#48 Compact Clusters enhancement
  enhancements/compact-clusters.md
Labels: approved, lgtm, size/L

#1 add cert auto-recovery for kube-apiserver and kube-controller-manager design
  enhancements/kube-apiserver/auto-cert-recovery.md
Labels: approved, lgtm, size/L

#69 Move olm/operator-bundle.md to enhancements/olm
  enhancements/olm/operator-bundle.md
Labels: approved, lgtm, size/XS

#70 Operator Bundle metadata updates
  enhancements/olm/operator-bundle.md
Labels: approved, lgtm, size/M

#73 fix cl forwarding to reference 'forward' plugin
  enhancements/cluster-logging/cluster-logging-log-forwarding.md
Labels: approved, lgtm, size/S

#76 Move the networking enhancements to the right subdir
  enhancements/network/20190903-SRIOV-GA.md
  enhancements/network/20190919-OVN-Kubernetes.md
Labels: approved, lgtm, size/XS

#71 Enhancement for disconnected mirror of OLM catalogs
  enhancements/oc/olm-mirroring.md
Labels: approved, lgtm, size/L

#63 add global cluster egress proxy enhancement
  enhancements/proxy/global-cluster-egress-proxy.md
Labels: approved, lgtm, size/L

#84 Machine health check follow up
  enhancements/machine-health-checking.md
Labels: approved, lgtm, size/M

#85 Add removed Implementation Details section to mhc
  enhancements/machine-health-checking.md
Labels: approved, lgtm, size/XS

#86 Add more impl details to machine health checking
  enhancements/machine-health-checking.md
Labels: approved, lgtm, size/M

#88 Add audit logs to cluster-logging-log-forwarding enhancement proposal
  enhancements/cluster-logging/cluster-logging-log-forwarding.md
Labels: approved, lgtm, size/S

#37 Add enhancements proposal for kernel args day 1 support in the MCO
  enhancements/mco-kargs-day1-support.md
Labels: approved, lgtm, size/L

#89 Clean up formatting in the enhancement
  enhancements/network/20190919-OVN-Kubernetes.md
Labels: approved, lgtm, size/S

#94 Add some details to machine phases
  enhancements/machine-instance-lifecycle.md
Labels: approved, lgtm, size/S

#95 Move machine API proposals into its own repo
  enhancements/machine-api/machine-health-checking.md
  enhancements/machine-api/machine-instance-lifecycle.md
Labels: approved, lgtm, size/XS

#45 Remove registry on Baremetal, RHV, and VSphere
  image-registry/remove-registry-baremetal.md
Labels: approved, lgtm, size/L

#93 Introduce LogForwarding Resource
  enhancements/cluster-logging/cluster-logging-log-forwarding.md
Labels: approved, lgtm, size/M

#83 Automated Service CA Rotation
  enhancements/automated-service-ca-rotation.md
Labels: approved, lgtm, size/L
