Repository openshift/enhancements, pull requests merged in 2020-03, with the labels that each got.

#211 RHCOS: Complex Devices via Ignition
  enhancements/rhcos/complex-devices.md
Labels: approved, lgtm, size/L

#234 monitoring: user-workload-monitoring GA
  enhancements/monitoring/user-workload-monitoring.md
Labels: approved, lgtm, size/L

#225 Forwarder enhancement proposal.
  enhancements/cluster-logging/cluster-logging-log-forwarding.md
Labels: approved, lgtm, size/L

#186 Machine API autoscaling from/to zero proposal
  enhancements/machine-api/autoscaling-from-to-zero.md
Labels: approved, lgtm, size/L

#199 Add spot-instances machine-api proposal
  enhancements/machine-api/spot-instances.md
Labels: approved, lgtm, size/L

#241 Update elasticsearch index alias names for log types.
  enhancements/cluster-logging/cluster-logging-es-rollover-data-design.md
Labels: approved, lgtm, size/S

#139 Add a proposal for CSI driver installation
  enhancements/storage/csi-driver-install.md
Labels: approved, lgtm, size/L

#245 Update and clarify Manila CSI integration
  enhancements/storage/manila-csi-driver-operator.md
Labels: approved, lgtm, size/M

#242 Add proposal for AWS EBS CSI driver operator
  enhancements/storage/csi-ebs-operator.md
Labels: approved, lgtm, size/L

#247 Adds design proposal to auto provision local PVs in LSO
  enhancements/local-storage/automatic-detection.md
Labels: approved, lgtm

#248 Add section about driver operator uninstall
  enhancements/storage/csi-driver-install.md
Labels: approved, lgtm

#249 Describes ETCD Encryption For Separate OAuth APIs
  enhancements/etcd/etcd-encryption-for-separate-oauth-apis.md
Labels: approved, lgtm

#251 Add Lifecycle label to Spot Instances enhancement
  enhancements/machine-api/spot-instances.md
Labels: approved, lgtm

#236 explain CRC current state
  enhancements/installer/crc.md
Labels: approved, lgtm, size/M

#258 Documenting pull secrets path on master nodes
  enhancements/node-pull-credentials/pull-credentials.md
Labels: approved, lgtm

#163 installer: AWS custom region and endpoints
  enhancements/installer/aws-custom-region-and-endpoints.md
Labels: approved, lgtm, size/L

#252 Adds Enhancement Proposal for Ingress Wildcard Routing
  enhancements/ingress/wildcard-admission-policy.md
Labels: approved, lgtm

#261 Remove dots to index management
  enhancements/cluster-logging/cluster-logging-es-rollover-data-design.md
Labels: approved, lgtm

#262 Removes Status From Ingress Wildcard Admission Policy
  enhancements/ingress/wildcard-admission-policy.md
Labels: approved, lgtm
