Repository openshift/enhancements, pull requests merged in 2020-10, with the labels that each got.

#484 Initial flexibly-enforcing-product-build-constraints-in-ci
  enhancements/art/flexibly-enforcing-product-build-constraints-in-ci.md
  enhancements/art/inconsistent.gif
Labels: approved, lgtm

#478 add a tool to report on activity in this repository
  tools/README.md
  tools/config/config.go
  tools/enhancements/summary.go
  tools/go.mod
  tools/go.sum
  tools/report/main.go
  tools/stats/stats.go
Labels: approved, lgtm

#454 Enhancement for User Space Pod Interface and API Library
  enhancements/network/user-space-pod-iface-and-api-library.md
Labels: approved, lgtm

#476 Add weekly newsletters to the repository
  this-week/2020-08-28.md
  this-week/2020-09-04.md
  this-week/2020-09-11.md
  this-week/2020-09-18.md
  this-week/README.md
Labels: approved, lgtm

#490 reformat summaries in newsletter
  tools/enhancements/summary.go
  tools/go.mod
  tools/go.sum
  tools/report/main.go
Labels: approved, lgtm

#491 this-week: Add newsletter for 2020-10-02
  this-week/2020-10-02.md
Labels: approved, lgtm

#466 Enhancement: Internationalization for console
  enhancements/console/internationalization.md
Labels: approved, lgtm

#469 enhancement: console user settings
  enhancements/console/user-settings.md
Labels: approved, lgtm

#494 Update standalone kube-proxy ports
  enhancements/network/host-port-registry.md
Labels: approved, lgtm

#498 tools: improve formatting of weekly report
  .gitignore
  tools/.golangci.yml
  tools/Makefile
  tools/enhancements/summary.go
  tools/report/main.go
  tools/stats/stats.go
Labels: approved, lgtm

#499 this-week: add newsletter for 2020-10-09
  this-week/2020-10-09.md
Labels: approved, lgtm

#495 Updates to SLO for baremetal enhancement proposal
  enhancements/baremetal/an-slo-for-baremetal.md
Labels: approved, lgtm

#453 network: Add a high level BGP use cases overview
  enhancements/network/bgp-overview.md
  guidelines/enhancement_template.md
Labels: approved, lgtm

#502 this-week: Add 2020-10-15
  this-week/2020-10-15.md
Labels: approved, lgtm

#437 Add OpenStack Cinder CSI driver support
  enhancements/storage/cinder-csi-driver-operator.md
Labels: approved, lgtm

#441 enhancement: dynamic plugins for console
  enhancements/console/dynamic-plugins.md
Labels: approved, lgtm

#419 Enhancement for adding a manifest annotation for object removal
  enhancements/update/object-removal-manifest-annotation.md
Labels: approved, lgtm

#506 Add Network Edge members to approvers
  OWNERS
Labels: approved, lgtm

#432 Add Default Apps Domain enhancement
  enhancements/ingress/default-apps-domain.md
Labels: approved, lgtm, tide/merge-method-squash

#510 Define current installation profile name
  enhancements/update/cluster-profiles.md
Labels: approved, lgtm

#517 this week 2020-10-23
  this-week/2020-10-23.md
Labels: approved, lgtm

#503 WMCO upgrade enhancement update
  enhancements/windows-containers/windows-machine-config-operator-upgrades.md
Labels: approved, lgtm

#385 rhcos/extensions: Guidance on adding extensions
  enhancements/rhcos/extensions.md
Labels: approved, lgtm, lifecycle/stale

#500 Automated downstream Operator SDK into the OpenShift ecosystem.
  enhancements/operator-sdk/downstream-operator-sdk.md
Labels: approved, lgtm

#448 Proposal to enable JSON data processing
  enhancements/cluster-logging/cluster-logging-es-pipeline-processing.md
Labels: approved, lgtm

#425 describe e2e observer pods
  enhancements/test-platform/e2e-observer-pods.md
Labels: approved, lgtm

#352 Rework CSI driver installation to CVO / cluster-storage-operator
  enhancements/storage/csi-driver-install.md
Labels: approved, lgtm, lifecycle/stale

#521 Update CSI repo names
  enhancements/storage/csi-driver-install.md
Labels: approved, lgtm

#523 this-week: 2020-10-30
  this-week/2020-10-30.md
Labels: approved, lgtm
