Repository openshift/enhancements, pull requests merged in 2020-08, with the labels that each got.

#390 Update spot termination handler design to use conditions
  enhancements/machine-api/spot-instances.md
Labels: approved, lgtm

#230 Propose a unicast method of configuring keepalived for Baremetal IPI
  enhancements/baremetal/baremetal-keepalived-unicast.md
Labels: approved, lgtm, size/L

#318 Rename "Projectedresource" to "Share"
  enhancements/cluster-scope-secret-volumes/csi-driver-host-injections.md
Labels: approved, lgtm

#418 Clarify cluster profile usage requirements
  enhancements/cvo/cluster-profiles.md
Labels: approved, lgtm

#202 IBM Public Cloud Support
  enhancements/ibm-public-cloud/ibm-public-cloud-support.md
Labels: approved, lgtm, size/L

#384 Subscription Content Access
  enhancements/subscription-content/subscription-content-access.md
Labels: approved, lgtm

#334 Improve oc awareness of ImageContentSourcePolicy
  enhancements/oc/image-content-source-policy-awareness.md
Labels: approved, lgtm

#420 auth/oauth-resource-storage: switch to sha256~ to be RF6750 conformant
  enhancements/authentication/oauth-resource-storage.md
Labels: approved, lgtm

#422 enhancements/update: Consolidate update-related enhancements
  enhancements/update/available-update-metadata.md
  enhancements/update/cluster-profiles.md
  enhancements/update/clusteroperator-resource-handling.md
  enhancements/update/distribute-secondary-metadata-as-container-image.md
  enhancements/update/ibm-public-cloud-support.md
Labels: approved, lgtm

#434 Update title to cluster-logging-es-init
  enhancements/cluster-logging/cluster-logging-move-init-to-es-operator.md
Labels: approved, lgtm

#160 Minor updates
  enhancements/cluster-logging/cluster-logging-es-rollover-data-design.md
Labels: approved, lgtm, size/XS

#102 Providing background for Baremetal IPI based enhancements
  enhancements/baremetal/baremetal.md
Labels: approved, lgtm, size/L

#113 enhancements: Remove "[optional]" from headers
  enhancements/authentication/configuring-webhook-token-authenticators.md
  enhancements/authentication/oauth-resource-storage.md
  enhancements/authentication/separate-oauth-resources.md
  enhancements/autoscaling/cluster-resource-overrides.md
  enhancements/baremetal/baremetal-provisioning-config.md
  enhancements/builds/node-cache-for-builds.md
  enhancements/cluster-logging/forwarder-tagging.md
  enhancements/cluster-scope-secret-volumes/csi-driver-host-injections.md
  enhancements/dns/plugins.md
  enhancements/etcd/cluster-etcd-operator.md
  enhancements/etcd/disaster-recovery-with-ceo.md
  enhancements/etcd/etcd-encryption-for-separate-oauth-apis.md
  enhancements/etcd/storage-migration-for-etcd-encryption.md
  enhancements/ingress/openshift-route-admission-policy.md
  enhancements/ingress/user-defined-default-ingress-controller.md
  enhancements/ingress/wildcard-admission-policy.md
  enhancements/installer/assisted-installer-bare-metal-validations.md
  enhancements/installer/aws-custom-region-and-endpoints.md
  enhancements/installer/aws-customer-provided-subnets.md
  enhancements/installer/aws-permissions-check-bypass.md
  enhancements/installer/azure-support-known-cloud-environments.md
  enhancements/installer/connected-assisted-installer.md
  enhancements/installer/crc.md
  enhancements/installer/gcp-customer-provided-subnets.md
  enhancements/installer/gcp-private-clusters.md
  enhancements/kube-apiserver/audit-policy.md
  enhancements/kube-apiserver/bound-sa-tokens.md
  enhancements/kube-apiserver/certificates.md
  enhancements/kube-apiserver/stability-point-to-point-network-check.md
  enhancements/kube-apiserver/tls-config.md
  enhancements/machine-config/ignition-spec-dual-support.md
  enhancements/machine-config/mco-kargs-day1-support.md
  enhancements/machine-config/user-data-secret-managed.md
  enhancements/mcd-reboot-exceptions.md
  enhancements/multi-arch/samples.md
  enhancements/network/allow-external-ip-overrides.md
  enhancements/network/baremetal-networking.md
  enhancements/network/host-level-openvswitch.md
  enhancements/oc/icsp-registry-scoped.md
  enhancements/oc/inspect.md
  enhancements/oc/must-gather.md
  enhancements/proxy/global-cluster-egress-proxy.md
  enhancements/samples/removed-bootstrapping.md
  enhancements/security/file-integrity-operator.md
  enhancements/service-catalog/prepare-service-catalog-and-brokers-for-removal.md
  enhancements/service-catalog/service-catalog-and-broker-removal.md
  enhancements/storage/csi-certification.md
  enhancements/storage/csi-cloning.md
  enhancements/storage/csi-ebs-operator.md
  enhancements/storage/csi-resize.md
  enhancements/storage/csi-snapshot.md
  enhancements/subscription-content/subscription-content-access.md
Labels: approved, lgtm, size/M

#114 enhancements/template: Fix maturity-levels link
  enhancements/api-review/add-unqualified-search-registries.md
  enhancements/autoscaling/cluster-resource-overrides.md
  enhancements/installer/assisted-installer-bare-metal-validations.md
  enhancements/installer/aws-custom-region-and-endpoints.md
  enhancements/installer/aws-permissions-check-bypass.md
  enhancements/installer/azure-internal-with-user-defined-routing.md
  enhancements/installer/azure-support-known-cloud-environments.md
  enhancements/installer/connected-assisted-installer.md
  enhancements/installer/gcp-private-clusters.md
  enhancements/kube-apiserver/audit-policy.md
  enhancements/kube-apiserver/stability-point-to-point-network-check.md
  enhancements/monitoring/user-workload-monitoring.md
  enhancements/oc/icsp-registry-scoped.md
  guidelines/enhancement_template.md
Labels: approved, lgtm, size/S

#349 [olm-metrics] Collect data on reachability of Operator SDK from bundle image
  enhancements/olm/report-sdk-operators.md
Labels: approved, lgtm

#57 SR-IOV GA: add default route overwrite example
  enhancements/network/20190903-SRIOV-GA.md
Labels: approved, lgtm, size/S

#435 baremetal: Address comments on #102
  enhancements/baremetal/baremetal.md
Labels: approved, lgtm

#219 Update the Baremetal Provisioning CRD enhancement proposal to match implementation
  enhancements/baremetal/baremetal-provisioning-config.md
Labels: approved, lgtm, size/M

#81 Add enhancement related to adding Vertical Pod Autoscaler to OperatorHub
  enhancements/vertical-pod-autoscaler/add-vpa-to-operator-hub.md
Labels: approved, lgtm, size/L

#74 Operator Registry bundle metadata parsing
  enhancements/olm/operator-registry.md
Labels: approved, lgtm, size/S

#439 vpa: Update enhancment to implemented
  enhancements/vertical-pod-autoscaler/add-vpa-to-operator-hub.md
Labels: approved, lgtm

#264 Updated ref/hyperlink for build-machinary-go
  enhancements/operator-dev-doc.md
Labels: approved, lgtm

#445 Cluster Profiles support for IBM Cloud
  enhancements/update/ibm-public-cloud-support.md
Labels: approved, lgtm

#446 IBM Cloud: fix wording on manifests for cluster profiles
  enhancements/update/ibm-public-cloud-support.md
Labels: approved, lgtm

#451 default-ingress-cert-configmap: implemented
  enhancements/ingress/default-ingress-cert-configmap.md
Labels: approved, lgtm

#405 Add an enhancement for adding a VRF CNI
  enhancements/network/vrf-cni.md
Labels: approved, lgtm

#455 network: add port registry
  enhancements/network/host-port-registry.md
Labels: approved, lgtm

#394 Discuss host network configuration interfaces
  enhancements/host-network-configuration.md
Labels: approved, lgtm
