Repository openshift/enhancements, pull requests merged in 2020-01, with the labels that each got.

#130 Add a roadmap to OpenShift
  README.md
  ROADMAP.md
  enhancements/README.md
Labels: approved, lgtm, size/L

#164 Update the olm enhancement document
  enhancements/olm/operator-bundle.md
Labels: approved, lgtm, size/S

#170 Add API for CSI snapshot operator
  enhancements/storage/csi-snapshot.md
Labels: approved, lgtm, size/M

#13 config ClusterResourceOverrides as mutating admission webhook via OLM
  autoscaling/cluster-resource-overrides.md
Labels: approved, lgtm, size/L

#100 Update service ca rotation risks with testing strategy
  enhancements/automated-service-ca-rotation.md
Labels: approved, lgtm, size/M

#75 separate oauth API resources from the openshift-apiserver
  enhancements/authentication/separate-oauth-resources.md
Labels: approved, lgtm, size/L

#147 Cluster Logging Kibana 6 Multitenancy using OpenDistro
  enhancements/cluster-logging/cluster-logging-kibana-multitenancy.md
Labels: approved, lgtm, size/L

#180 Update enhancement to cover new direction
  enhancements/service-catalog/service-catalog-and-broker-removal.md
Labels: approved, lgtm, size/L

#179 Remove 'node.infra' logs
  enhancements/cluster-logging/cluster-logging-es-rollover-data-design.md
Labels: approved, lgtm, size/S

#150 Enable Bound Service Account Tokens
  enhancements/kube-apiserver/bound-sa-tokens.md
Labels: approved, lgtm, size/L

#183 add explanation of extended-platform-tests
  enhancements/testing/extended-platform-tests.md
Labels: approved, lgtm, size/L

#162 Add proposal for CSI certification suite
  enhancements/storage/csi-certification.md
Labels: approved, lgtm, size/L

#171 Marketplace API deprecation enhancement
  enhancements/olm/marketplace-api-deprecation.md
Labels: approved, lgtm, size/L

#181 automated service ca rotation: Propose extension of ca duration
  enhancements/authentication/automated-service-ca-rotation.md
Labels: approved, lgtm, size/S

#184 Enable service ca bundle injection for webhooks
  enhancements/authentication/service-ca-bundle-injection-for-admission-webhooks.md
  enhancements/service-ca-bundle-injection-for-admission-webhooks.md
Labels: approved, lgtm, size/L

#191 openstack-self-signed-certificates
  enhancements/security/openstack-self-signed-certificates.md
Labels: approved, lgtm, size/L

#97 enhancement: add ignition dual spec 2/3 support
  enhancements/ignition-spec-dual-support.md
Labels: approved, lgtm, size/L

#187 Expand ca bundle injection enhancement to cover all supported types
  enhancements/authentication/service-ca-bundle-injection-for-admission-webhooks.md
  enhancements/authentication/service-ca-bundle-injection.md
Labels: approved, lgtm, size/L

#192 Update Kuryr information on SSC doc
  enhancements/security/openstack-self-signed-certificates.md
Labels: approved, lgtm, size/XS

#136 Using node pull credentials during builds, image stream imports and pull-through
  enhancements/node-pull-credentials/pull-credentials.md
Labels: approved, lgtm, size/L

#195 Replace Brad as storage owner
  OWNERS
Labels: approved, lgtm, size/XS

#194 Update CSI Certification proposal
  enhancements/storage/csi-certification.md
Labels: approved, lgtm, size/XS

#172 DEVEXP-507: add samples operator proposal for bootstrapping as removed for ipv6/d…
  enhancements/samples/removed-bootstrapping.md
Labels: approved, lgtm, size/L
