Repository openshift/enhancements, pull requests merged in 2020-05, with the labels that each got.

#306 Update MHC annotation
  enhancements/machine-api/machine-health-checking.md
Labels: approved, lgtm

#290 Document procedure for creating new base branch in openshift/kubernetes
  enhancements/rebase.md
Labels: approved, lgtm

#232 Elasticsearch init logic in the ES operator
  .gitignore
  enhancements/cluster-logging/cluster-logging-move-init-to-es-operator.md
Labels: approved, lgtm, size/M

#308 This change the installer custom region enhancement to align with the code
  enhancements/installer/aws-custom-region-and-endpoints.md
Labels: approved, lgtm

#281 Fix the default issuer for bound sa tokens
  enhancements/kube-apiserver/bound-sa-tokens.md
Labels: approved, lgtm

#313 introduce guidelines directory
  enhancements/scheduling/gang-scheduling.md
  guidelines/template.md
Labels: approved, lgtm

#314 rename template to enhancement_template
  guidelines/template.md
Labels: approved, lgtm

#320 guildelines/README: Shift from enhancements/README
  README.md
  enhancements/README.md
  guidelines/README.md
Labels: approved, lgtm

#288 Minor typo fixed.
  enhancements/cluster-logging/cluster-logging-log-forwarding.md
Labels: approved, lgtm

#210 Rebase RHEL CoreOS 4.5 on Fedora CoreOS Live ISO/installer
  enhancements/rhcos/liveisoinstall.md
Labels: approved, lgtm, size/M

#336 Update OWNERS to include baremetal IPI architects and team leads
  OWNERS
Labels: approved, lgtm

#335 Bootstrap an OpenShift conventions document for the project
  CONVENTIONS.md
Labels: approved, lgtm

#337 Minor cleanup of rebase enhancement
  enhancements/rebase.md
Labels: approved, lgtm

#257 Add audit policy enhancement
  enhancements/kube-apiserver/audit-policy.md
Labels: approved, lgtm

#340 enhancements/monitoring/user-workload-monitoring.md: Remove mentions of
  enhancements/monitoring/user-workload-monitoring.md
Labels: approved, lgtm

#329 Update ClusterLogForwarder enhancement proposal to reflect current status.
  enhancements/cluster-logging/cluster-logging-log-forwarding.md
Labels: approved, lgtm

#149 create all clusteroperators in the CVO payload immediately
  enhancements/cvo/clusteroperator-resource-handling.md
Labels: approved, lgtm, size/L

#344 CONVENTIONS: Add taints and tolerations
  CONVENTIONS.md
Labels: approved, lgtm
