Repository openshift/enhancements, pull requests merged in 2020-07, with the labels that each got.

#237 Adds proposal for AutoDetection on LSO
  enhancements/local-storage/automatic-detection.md
Labels: approved, lgtm, size/L

#324 aws-permissions-check-bypass
  enhancements/installer/aws-permissions-check-bypass.md
Labels: approved, lgtm

#374 Generate ImageContentSourcePolicy scoped to a registry
  enhancements/oc/icsp-registry-scoped.md
Labels: approved, lgtm

#159 Domain-specific reboot minimisation enhancement
  enhancements/mcd-reboot-exceptions.md
Labels: approved, lgtm, size/L

#391 Expand details of the Machine Health Check proposal
  enhancements/machine-api/machine-health-checking.md
Labels: approved, lgtm

#323 enhancement: Secure OAuth Resource Storage
  enhancements/authentication/oauth-resource-storage.md
Labels: approved, lgtm

#342 OpenStack Bring Your Own External Connectivity
  enhancements/installer/openstack-no-fip-install.md
Labels: approved, lgtm

#378 Enhancement for adding UnqualifiedSearchRegitries to the Image CR
  enhancements/api-review/add-unqualified-search-registries.md
Labels: approved, lgtm

#326 oVirt UPI enhancement proposal
  enhancements/installer/ovirt-rhv-upi.md
Labels: approved, lgtm

#123 enhancements/update/available-update-metadata: Propose a new enhancement
  enhancements/update/available-update-metadata.md
Labels: approved, lgtm, size/L

#8 Update README wording
  README.md
Labels: approved, lgtm, size/XS

#200 Cluster Profiles
  enhancements/cvo/cluster-profiles.md
Labels: approved, lgtm, size/M

#407 LOG-717: Change "output" to "forwarder" in fluentd_tuning.md
  enhancements/cluster-logging/fluentd-tuning.md
Labels: approved, lgtm

#409 LOG-717: fluentd_tuning.md to use lowerCamelCase for API fields
  enhancements/cluster-logging/fluentd-tuning.md
Labels: approved, lgtm

#402 Update "last-updated" in document info.
  enhancements/cluster-logging/cluster-logging-log-forwarding.md
Labels: approved, lgtm

#410 Update to unqualified-search-registries enhancement
  enhancements/api-review/add-unqualified-search-registries.md
Labels: approved, lgtm

#321 installer: azure support all known cloud environments
  enhancements/installer/azure-support-known-cloud-environments.md
Labels: approved, lgtm

#408 enhancements/update/available-update-metadata: 'url' docstring context
  enhancements/update/available-update-metadata.md
Labels: approved, lgtm

#383 add a document for machine api usage telemetry
  enhancements/machine-api/machine-api-usage-telemetry.md
Labels: approved, lgtm

#413 Update spot instances status
  enhancements/machine-api/spot-instances.md
Labels: approved, lgtm

#175 Design proposal for implementing helm support in OpenShift Console
  enhancements/helm3/assets/charts-repo.png
  enhancements/helm3/assets/dev-catalog.png
  enhancements/helm3/assets/helm-endpoints.svg
  enhancements/helm3/assets/image-console-config.png
  enhancements/helm3/assets/olm-no-charts.png
  enhancements/helm3/assets/openshift-administration-cluster-settings.png
  enhancements/helm3/console.md
Labels: approved, lgtm, size/M

#398 Windows Machine Config Operator upgrade design
  enhancements/windows-containers/windows-machine-config-operator-upgrades.md
Labels: approved, lgtm

#310 update: distribute cincinnati-graph-data as container images
  enhancements/update/distribute-secondary-metadata-as-container-image.md
Labels: approved, lgtm

#404 clarify behavior for the aws permissions bypass proposal
  enhancements/installer/aws-permissions-check-bypass.md
Labels: approved, lgtm

#370 Add logging-headers enhancement
  enhancements/ingress/logging-headers.md
Labels: approved, lgtm
