Repository openshift/enhancements, pull requests merged in 2020-06, with the labels that each got.

#348 Update auto recovery to match what's implemented
  enhancements/kube-apiserver/auto-cert-recovery.md
Labels: approved, lgtm

#332 Add enhancement doc for Cluster Autoscaler Operator
  enhancements/machine-api/cluster-autoscaler-operator.md
Labels: approved, lgtm

#311 Add guidelines on PR + commit text
  guidelines/commit_and_pr_text.md
Labels: approved, lgtm

#353 Add the correct casing of OpenShift to conventions
  CONVENTIONS.md
Labels: approved, lgtm

#354 Fix all instances of Openshift to OpenShift
  enhancements/baremetal/baremetal-provisioning-config.md
  enhancements/etcd/disaster-recovery-with-ceo.md
  enhancements/machine-api/spot-instances.md
  enhancements/machine-config/ignition-spec-dual-support.md
  enhancements/network/allow-external-ip-overrides.md
  enhancements/security/openstack-self-signed-certificates.md
  enhancements/storage/csi-driver-install.md
  enhancements/storage/manila-csi-driver-operator.md
Labels: approved, lgtm

#345 Add proposal for defaulting/validating machine API providerSpec
  enhancements/machine-api/defaulting-validating.md
Labels: approved, lgtm

#293 dual-stack networking
  enhancements/network/dual-stack.md
Labels: approved, lgtm

#358 Fix README link
  enhancements/README.md
Labels: approved, lgtm

#338 installer: add azure-internal-with-user-defined-routing enahncement
  enhancements/installer/azure-internal-with-user-defined-routing.md
Labels: approved, lgtm

#351 Add enhancement for Cluster Autoscaler Machine API integration
  enhancements/machine-api/cluster-autoscaler-integration.md
Labels: approved, lgtm

#364 Windows Machine Config Operator design
  enhancements/windows-containers/ansible-dev-preview.md
  enhancements/windows-containers/windows-machine-config-operator.md
Labels: approved, lgtm

#148 DNS and LB services in cluster for non-cloud IPI
  enhancements/network/baremetal-networking.md
Labels: approved, lgtm, size/L

#289 stability: point to point network check
  enhancements/kube-apiserver/stability-point-to-point-network-check.md
Labels: approved, lgtm

#317 rhcos/extensions: Support for CoreOS extensions
  enhancements/rhcos/extensions.md
Labels: approved, lgtm

#347 LOG-751: Initial proposal for fluentd performance tweaks in logging.
  enhancements/cluster-logging/fluentd-tuning.md
Labels: approved, lgtm

#355 LOG-717: Forwader Tagging Initial Proposal
  enhancements/cluster-logging/forwarder-tagging.md
Labels: approved, lgtm

#381 Minor updates to recent proposals.
  enhancements/cluster-logging/fluentd-tuning.md
  enhancements/cluster-logging/forwarder-tagging.md
Labels: approved, do-not-merge/hold, lgtm

#142 Configuring Webhook Token Authenticators
  enhancements/authentication/configuring-webhook-token-authenticators.md
Labels: approved, lgtm, size/L

#372 move open questions section lower in the template
  guidelines/enhancement_template.md
Labels: approved, lgtm

#376 connected assisted installer
  enhancements/installer/connected-assisted-installer.md
Labels: approved, lgtm

#291 improved static networking configuration
  enhancements/rhcos/static-networking-enhancements.md
Labels: approved, lgtm

#377 Autsocaler CAPI integration: Link Machine Controller to code
  enhancements/machine-api/cluster-autoscaler-integration.md
Labels: approved, lgtm

#212 baremetal: propose a new Second Level Operator for bare metal
  enhancements/baremetal/an-slo-for-baremetal.md
Labels: approved, lgtm, size/L

#386 baremetal: enhancement for optional provisioning network
  enhancements/baremetal/baremetal-provisioning-optional.md
Labels: approved, lgtm

#387 Add dhellmann to OWNERS
  OWNERS
Labels: approved, lgtm

#388 validation changes for assisted bare metal deployments
  enhancements/installer/assisted-installer-bare-metal-validations.md
Labels: approved, lgtm

#368 MCO: manage machines userdata secret
  enhancements/machine-config/user-data-secret-managed.md
Labels: approved, lgtm
