Repository openshift/enhancements, pull requests merged in 2020-02, with the labels that each got.

#197 shuffle some files around to fix the directory structure
  enhancements/api-review/centralized-manifest-openapi-generation.md
  enhancements/authentication/service-ca-bundle-injection-for-admission-webhooks.md
  enhancements/autoscaling/cluster-resource-overrides.md
  enhancements/fedramp/compliance-operator.md
  enhancements/ingress/openshift-route-admission-policy.md
  enhancements/ingress/user-defined-default-ingress-controller.md
  enhancements/machine-config/ignition-spec-dual-support.md
  enhancements/machine-config/mco-kargs-day1-support.md
  enhancements/oc/must-gather.md
  enhancements/rhcos/automated-policy-based-disk-encryption.md
  enhancements/template.md
Labels: approved, lgtm, size/XS

#189 Summarize gang scheduling implementation and describe how to deploy it in OpenShift
  scheduling/gang-scheduling.md
Labels: approved, lgtm, size/L

#56 etcd: cluster-etcd-operator
  enhancements/etcd/cluster-etcd-operator.md
Labels: approved, lgtm, size/XL

#193 service-ca-rotation: Ensure pod restart before expiry of pre-rotation CA
  enhancements/authentication/automated-service-ca-rotation.md
Labels: approved, lgtm, size/M

#204 Update file-integrity-operator enhancement
  enhancements/security/file-integrity-operator.md
Labels: approved, lgtm, size/M

#213 Cleanup automated service ca rotation enhancement
  enhancements/authentication/automated-service-ca-rotation.md
Labels: approved, lgtm, size/M

#166 enhancements: support real-time kernels
  enhancements/support-for-realtime-kernel.md
Labels: approved, lgtm, size/L

#207 describe etcd 4.3 to 4.4 upgrade/downgrade
  enhancements/etcd/cluster-etcd-operator.md
Labels: approved, lgtm, size/M

#218 bring the etcd operator document closer to up-to-date
  enhancements/etcd/cluster-etcd-operator.md
Labels: approved, lgtm, size/L

#217 Adding enhancements for Disaster Recovery with the introduction of CEO
  enhancements/etcd/disaster-recovery-with-ceo.md
Labels: approved, lgtm, size/L

#178 user-workload-monitoring: be more accurate about alerts & silences enpoints
  enhancements/monitoring/user-workload-monitoring.md
Labels: approved, lgtm

#206 Add machine lifecycle diagram
  enhancements/machine-api/machine-instance-lifecycle.md
  enhancements/machine-api/machine-lifecycle.plantuml
  enhancements/machine-api/machine-lifecycle.png
Labels: approved, lgtm, size/M

#227 Fix typo
  enhancements/storage/csi-certification.md
Labels: approved, lgtm, size/XS

#220 add list of known etcd tests we need
  enhancements/etcd/cluster-etcd-operator.md
Labels: approved, lgtm, size/S

#233 update the etcd operator with exceptional scenarios
  enhancements/etcd/cluster-etcd-operator.md
Labels: approved, lgtm, size/M
