Repository openshift/enhancements, pull requests merged in 2021-12, with the labels that each got.

#969 enhancements/update: Set OWNERS for update-focused enhancements
  enhancements/update/OWNERS
Labels: lgtm, approved

#970 add tremes to owners
  OWNERS
Labels: lgtm, approved

#902 Add swap support to OpenShift
  enhancements/kubelet/node-swap.md
Labels: lgtm, approved, priority/important-soon

#951 CONVENTIONS: Add OpenShift-specific API conventions
  CONVENTIONS.md
Labels: lgtm, approved

#960 Insights pulling SCA certs - graduation criteria update
  enhancements/insights/pulling-sca-certs-from-ocm.md
Labels: lgtm, approved

#963 Proposal to allow MTU changes with rolling reboots
  enhancements/network/allow-mtu-changes.md
Labels: lgtm, approved

#939 [OCPNODE-725] Control Group v2 Enablement on New Clusters
  enhancements/machine-config/mco-cgroupsv2-support.md
Labels: lgtm, approved

#973 this-week: 2021-12-03
  this-week/2021-12-03.md
Labels: lgtm, approved

#975 Move NodeSwap to TechPreviewNoUpgrade feature set
  enhancements/kubelet/node-swap.md
Labels: lgtm, approved

#940 [LOG-1815] Enhancement proposal: Add alerts and rules for operator-managed LokiStack
  enhancements/cluster-logging/loki-observability.md
Labels: lgtm, approved

#965 CONVENTIONS: Include 33% option for DaemonSet maxUnavailable
  CONVENTIONS.md
Labels: lgtm, approved

#976 Disable the no-trailing-spaces linter rule
  .markdownlint-cli2.yaml
Labels: lgtm, approved

#968 add audit spec for password authenticator flow
  enhancements/authentication/login-logout-events.md
Labels: lgtm, approved

#974 dev-guide/cluster-version-operator/dev: Doc TechPreview feature gate annotations
  dev-guide/cluster-version-operator/dev/object-deletion.md
  dev-guide/cluster-version-operator/dev/operators.md
Labels: lgtm, approved

#979 typo in externaldns-operator
  enhancements/dns/externaldns-operator.md
Labels: lgtm, approved

#921 Enhancement proposal for Network Observability
  enhancements/arch22.drawio.svg
  enhancements/network-observability.md
Labels: lgtm, approved

#982 dev-guide/cluster-version-operator/dev/clusterversion: Drop version from 'group'
  dev-guide/cluster-version-operator/dev/clusterversion.md
Labels: lgtm, approved

#791 Support RAID and BIOS configuration for baremetal IPI deployments
  enhancements/baremetal/baremetal-config-raid-and-bios.md
Labels: lgtm, approved, ok-to-test

#983 this-week: 2021-12-10
  this-week/2021-12-10.md
Labels: lgtm, approved

#984 Update OWNERS
  OWNERS
Labels: lgtm, approved

#962 WINC-505: Windows containerd runtime enablement
  enhancements/windows-containers/container-runtime-containerd.md
Labels: lgtm, approved

#961 Update KEP for vsphere CSI driver operator
  enhancements/storage/csi-vsphere-operator.md
Labels: lgtm, approved

#837 Conditional Data Gathering for Insights Operator
  enhancements/insights/conditional-data-gathering.md
Labels: lgtm, approved

#991 this-week: 2021-12-17
  this-week/2021-12-17.md
  tools/cmd/report.go
Labels: lgtm, approved
