Repository openshift/enhancements, pull requests merged in 2021-01, with the labels that each got.

#572 this-week: newsletter for 2020-12-18
  this-week/2020-12-18.md
Labels: approved, lgtm

#569 Bug 1908145: Add workloads localhost ports for recovery-controllers
  enhancements/network/host-port-registry.md
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#518 Enhancement proposal: Forwarding JSON logs.
  enhancements/cluster-logging/forwarding-json-structured-logs.md
Labels: approved, lgtm

#573 host-port-registry: "workers" → "nodes"
  enhancements/network/host-port-registry.md
Labels: approved, lgtm

#579 this-week: Add 2021-01-08 report
  this-week/2021-01-08.md
Labels: approved, lgtm

#424 updates Separate-OAuth-API-Resources enhancement to reflect the current state of the world
  enhancements/authentication/separate-oauth-resources.md
Labels: approved, lgtm, lifecycle/rotten

#560 single-node production deployment approach
  enhancements/single-node-production-deployment-approach.md
Labels: approved, lgtm

#555 Cluster High-availability Mode API
  enhancements/cluster-high-availability-mode-api.md
Labels: approved, lgtm

#430 Proposal for networkpolicy for multus interface (i.e. net-attach-def)
  enhancements/network/multi-networkpolicy.md
Labels: approved, lgtm

#584 Update Infrastructure topology from SingleNode to SingleReplica
  enhancements/cluster-high-availability-mode-api.md
Labels: approved, lgtm

#587 add risk about disruptive changes to single-node-production-deployment-approach
  enhancements/single-node-production-deployment-approach.md
Labels: approved, lgtm

#570 Enhancement Proposal: API to Forward Logs to CloudWatch
  enhancements/cluster-logging/forward_to_cloudwatch.md
Labels: approved, lgtm

#580 tools: filter PRs before printing report
  tools/report/main.go
Labels: approved, lgtm

#586 host-port-registry: Add IPsec
  enhancements/network/host-port-registry.md
Labels: approved, lgtm

#588 host-port-registry: add 6080 port
  enhancements/network/host-port-registry.md
Labels: approved, lgtm

#589 this week in enhancements 2021-01-15
  this-week/2021-01-15.md
Labels: approved, lgtm

#369 scheduling: Add new pod priority class
  enhancements/scheduling/priority-class.md
Labels: approved, lgtm, lifecycle/stale

#598 Update owners for Cluster Infrastructure team lead change
  OWNERS
Labels: approved, lgtm

#595 Add Control Plane MachineSets proposal
  enhancements/machine-api/control-plane-machinesets.md
Labels: approved, lgtm

#61 oVirt IPI enhancement document
  enhancements/platforms/ovirt-rhv-ipi.md
Labels: approved, lgtm, lifecycle/stale, size/L

#431 Update ptp proposal for multiple interfaces
  enhancements/ptp-time-integration.md
Labels: approved, lgtm

#599 convert from github/super-linter to markdownlint
  .github/workflows/linter.yml
  .markdownlint-cli2.yaml
  .markdownlint.yaml
  Makefile
  hack/Dockerfile.markdownlint
  hack/markdownlint.sh
Labels: approved, lgtm

#154 Add vSphere IPI
  enhancements/installer/vsphere-ipi.md
Labels: approved, lgtm, size/L

#600 this-week: Add 2021-01-22
  this-week/2021-01-22.md
Labels: approved, lgtm

#601 continue working on markdownlint
  enhancements/platforms/ovirt-rhv-ipi.md
  enhancements/ptp-time-integration.md
  enhancements/scheduling/priority-class.md
  hack/Dockerfile.markdownlint
Labels: approved, lgtm

#602 README.md: Document the priority/important-soon label usage
  README.md
Labels: approved, lgtm

#596 clarify wording about cluster machine approver for single-node
  enhancements/single-node-production-deployment-approach.md
Labels: approved, lgtm, priority/important-soon

#591 authentication: useroauthaccesstokens - don't remove system:oauth-token-deleters
  enhancements/authentication/allow-users-to-manage-their-own-tokens.md
Labels: approved, lgtm

#597 Add groupPrefix field to cloudwatch output type
  enhancements/cluster-logging/forward_to_cloudwatch.md
Labels: approved, lgtm

#605 cluster-high-availability-mode-api: clarify use of "infrastructure"
  enhancements/cluster-high-availability-mode-api.md
Labels: approved, lgtm

#604 tools: Show prioritized enhancements in the report
  hack/Dockerfile.markdownlint
  tools/report/main.go
  tools/stats/stats.go
Labels: approved, lgtm

#606 markdownlint: move install steps to reusable script
  enhancements/installer/vsphere-ipi.md
  hack/Dockerfile.markdownlint
  hack/install-markdownlint.sh
Labels: approved, lgtm

#607 add alex crawford to owners file
  OWNERS
Labels: approved, lgtm

#609 tools: include standard comments in PR activity count
  tools/README.md
  tools/stats/stats.go
Labels: approved, lgtm

#611 Fixed make lint permissions
  Makefile
Labels: approved, lgtm

#540 Installer/MCO: store pointer ignition customizations in MachineConfig
  enhancements/machine-config/custom-ignition-machineconfig.md
Labels: approved, lgtm

#610 tools: refactor to add subcommands
  tools/README.md
  tools/cmd/report.go
  tools/cmd/root.go
  tools/go.mod
  tools/go.sum
  tools/main.go
  tools/report/report.go
  tools/stats/stats.go
  tools/util/github.go
  tools/util/query.go
Labels: approved, lgtm

#614 this week newsletter 2021-01-29
  this-week/2021-01-29.md
Labels: approved, lgtm
