Repository openshift/enhancements, pull requests merged in 2021-02, with the labels that each got.

#615 refactor report tool
  tools/cmd/report.go
  tools/enhancements/summary.go
  tools/go.sum
  tools/report/report.go
  tools/stats/stats.go
  tools/stats/stats_test.go
Labels: approved, lgtm

#616 add a debug command to the report tool
  tools/cmd/debug.go
Labels: approved, lgtm

#619 tools: change debug command to show-pr
  tools/cmd/debug.go
  tools/cmd/show-pr.go
Labels: approved, lgtm

#620 tools: show old and stale enhancements by default
  tools/cmd/report.go
Labels: approved, lgtm

#621 tools: redefine stale in the report as having the lifecycle/stale label
  tools/cmd/report.go
  tools/stats/stats.go
Labels: approved, lgtm

#565 single-node deployment with bootstrap-in-place
  enhancements/installer/single-node-installation-bootstrap-in-place.md
Labels: approved, lgtm, priority/important-soon

#627 create single-node directory and move related enhancements into it
  enhancements/single-node/cluster-high-availability-mode-api.md
  enhancements/single-node/developer-cluster-profile.md
  enhancements/single-node/production-deployment-approach.md
Labels: approved, lgtm

#561 Initial proposal of "allow-from-router" NetworkPolicy
  enhancements/network/allow-from-router-networkpolicy.md
Labels: approved, lgtm

#592 Safer Cluster Upgrades for OLM Managed Operators
  enhancements/olm/max-openshift-versions-for-operators.md
Labels: approved, lgtm

#629 tools: do not show summaries of "other active" enhancements
  tools/cmd/report.go
Labels: approved, lgtm

#630 tools: move closed list to after active list
  tools/cmd/report.go
Labels: approved, lgtm

#608 WINC-482: Bring Your Own Windows Host design
  enhancements/windows-containers/bring-your-own-windows-host.md
Labels: approved, lgtm

#631 this-week: 2021-02-05
  this-week/2021-02-05.md
Labels: approved, lgtm

#632 tools: fix summary formatting
  tools/report/report.go
  tools/report/report_test.go
Labels: approved, lgtm

#633 tools: add make target for generating today's report
  Makefile
  tools/cmd/report.go
  tools/util/query.go
Labels: approved, lgtm

#585 EUS Upgrades MVP
  enhancements/update/eus-upgrades-mvp.md
Labels: approved, lgtm, priority/important-soon

#638 Allow other container runtimes for linting
  Makefile
Labels: approved, lgtm

#634 tools: wrap long lines to appease the linter
  tools/report/report.go
  tools/report/report_test.go
Labels: approved, lgtm

#639 tools: automatically upload this-week report to hackmd
  Makefile
  hack/Dockerfile.hackmd-cli
  hack/hackmd-cli.sh
Labels: approved, lgtm

#78 Add "Build OKD-on-Fedora-CoreOS in Prow" proposal
  enhancements/okd-on-fedora-coreos-in-prow.md
Labels: approved, lgtm, size/M

#644 OKD: Move proposal to `implementable`, clarify summary
  enhancements/okd-on-fedora-coreos-in-prow.md
Labels: approved, lgtm

#646 tools: extend show-pr command to include more details
  tools/cmd/report.go
  tools/cmd/show-pr.go
  tools/stats/stats.go
  tools/util/query.go
Labels: approved, lgtm

#473 Enhancement: Enable IPsec support in OVNKubernetes
  enhancements/network/ovn-kubernetes-ipsec.md
Labels: approved, lgtm

#438 Add ingress fault detection proposal
  enhancements/ingress/ingress-fault-detection.md
Labels: approved, lgtm

#612 Simplify initial cloudwatch proposal based on feedback.
  enhancements/cluster-logging/forward_to_cloudwatch.md
Labels: approved, lgtm

#648 this-week: 2021-02-12
  this-week/2021-02-12.md
  tools/cmd/report.go
  tools/cmd/show-pr.go
  tools/stats/stats.go
Labels: approved, lgtm

#653 Adding owners file for cluster-logging subdirectory
  enhancements/cluster-logging/OWNERS
Labels: approved, lgtm

#449 Add Tunable Router Buffer Sizes EP
  enhancements/ingress/tunable-router-buffer-sizes.md
Labels: approved, lgtm

#640 Ingress: Add GCP Global Access LB Proposal
  enhancements/ingress/gcp-lb-global-access.md
Labels: approved, lgtm

#645 eus-upgrades-mvp: Fix MCO constraints examples
  enhancements/update/eus-upgrades-mvp.md
Labels: approved, lgtm, priority/important-soon

#576 Move ES cert management into Elasticsearch Operator
  enhancements/cluster-logging/elasticsearch-cert-management.md
Labels: approved, lgtm

#658 ovn-kubernetes-ipsec: Update EP with small feature enhancements for OCP 4.8
  enhancements/network/ovn-kubernetes-ipsec.md
Labels: approved, lgtm

#659 this-week: 2021-02-19
  this-week/2021-02-19.md
Labels: approved, lgtm

#625 Simplify JSON forwarding proposal
  enhancements/cluster-logging/forwarding-json-structured-logs.md
Labels: approved, lgtm

#577 describe one-stop-shopping for exposing customized routes
  enhancements/ingress/custom-route-configuration.md
Labels: approved, lgtm
