Repository openshift/enhancements, pull requests merged in 2021-06, with the labels that each got.

#798 move developer docs to dev-guide
  dev-guide/kubernetes-rebase.md
  dev-guide/operators.md
  enhancements/README.md
Labels: approved, lgtm

#794 operator-dev-doc.md: add registry.ci.openshift.org
  dev-guide/operators.md
Labels: approved, lgtm

#759 workload-partitioning: reorganize
  enhancements/workload-partitioning/management-workload-partitioning.md
Labels: approved, lgtm, priority/important-soon

#788 CONVENTIONS.md: add PromQL query to calculate adequate memory request
  CONVENTIONS.md
Labels: approved, lgtm

#801 Fix the 'Kubernetest' typo in ROADMAP.md
  ROADMAP.md
Labels: approved, lgtm

#803 this-week: 2021-06-04
  this-week/2021-06-04.md
Labels: approved, lgtm

#790 Bug 1904507: Update vsphere-problem-detector with current implementation
  enhancements/storage/vsphere-problem-detector.md
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#799 machine-config/mco-network-configuration: fix markup
  enhancements/machine-config/mco-network-configuration.md
Labels: approved, lgtm

#780 Simplify and clarify JSON forwarding proposal, better examples.
  enhancements/cluster-logging/forwarding-json-structured-logs.md
Labels: approved, lgtm

#807 this-week: 2021-06-11
  this-week/2021-06-11.md
  tools/stats/stats.go
Labels: approved, lgtm

#808 Update the add page customization examples and add hint to use the snippet
  enhancements/console/customize-add-page.md
  enhancements/console/customize-add-page.png
Labels: approved, lgtm

#786 Add ExternalDNS Operator Enhancement Proposal
  enhancements/dns/externaldns-operator.md
Labels: approved, lgtm

#809 Updating annotation example due to k8s annotation key restrictions
  enhancements/cluster-logging/elasticsearch-cert-management.md
Labels: approved, lgtm

#642 Auto Node Sizing
  enhancements/kubelet/kubelet-node-sizing.md
Labels: approved, lgtm

#564 Allowing users to specify a delete policy based on amount of storage used within the ES cluster
  enhancements/cluster-logging/elasticsearch-percentage-index-management.md
Labels: approved, lgtm, lifecycle/stale

#792 kube-apiserver/audit: Add group customRules
  enhancements/kube-apiserver/audit-policy.md
Labels: approved, lgtm

#462 ingress: Add client-tls enhancement
  enhancements/ingress/client-tls.md
Labels: approved, lgtm

#818 kube-apiserver/audit: fix typo and mark implementable
  enhancements/kube-apiserver/audit-policy.md
Labels: approved, lgtm

#819 Update status of MCO Network Configuration as 'implemented'
  enhancements/machine-config/mco-network-configuration.md
Labels: approved, lgtm
