Repository openshift/enhancements, pull requests merged in 2021-11, with the labels that each got.

#945 readme: describe how to handle linter failures caused by template changes
  README.md
Labels: lgtm, approved

#946 host-port-registry: Reserve 9447 port for BMO webhook
  dev-guide/host-port-registry.md
Labels: lgtm, approved

#738 Installing OCP on ARM-Based Smart NICs
  enhancements/network/dpu/ocp-on-dpu.md
  enhancements/network/dpu/overview.md
Labels: lgtm, approved

#947 Insights pulling SCA certs - graduation criteria update
  enhancements/insights/pulling-sca-certs-from-ocm.md
Labels: lgtm, approved

#950 this-week: 2021-11-05
  this-week/2021-11-05.md
Labels: lgtm, approved

#475 enhancements/update/update-blocker-lifecycle: Propose a new enhancement
  enhancements/update/update-blocker-lifecycle/README.md
  enhancements/update/update-blocker-lifecycle/flow.dot
  enhancements/update/update-blocker-lifecycle/flow.svg
Labels: lgtm, approved, lifecycle/rotten

#890 Introduce DPU Network Operator
  enhancements/network/dpu/dpu-network-operator.md
Labels: lgtm, approved

#732 Add Smart NIC OVN offload enhancement
  enhancements/network/dpu/smart-nic-ovn-offload.md
Labels: lgtm, approved

#894 authentication/login-logout: initial enhancement
  enhancements/authentication/login-logout-events.md
Labels: lgtm, approved

#836 ETCD-58: Add enhancement for automated defragmentation
  enhancements/etcd/automated-defrag.md
Labels: lgtm, approved, lifecycle/rotten

#953 template: remove status field and replace with jira field
  guidelines/enhancement_template.md
Labels: lgtm, approved

#956 this-week: 2021-11-12
  this-week/2021-11-12.md
Labels: lgtm, approved

#881 LOG-1514: LokiStack CR extension for the gateway configuration
  enhancements/cluster-logging/loki-gateway-configuration.md
Labels: lgtm, approved

#957 describe how the CVO can support TechPreviewNoUpgrade
  enhancements/update/cvo-techpreview-manifests.md
Labels: lgtm, approved

#959 this-week: 2021-11-19
  this-week/2021-11-19.md
Labels: lgtm, approved

#862 Add Machine Deletion Hooks Proposal
  enhancements/machine-api/machine-deletion-hooks.md
Labels: lgtm, approved, priority/important-soon

#876 ingress: Add mutable-publishing-scope enhancement
  enhancements/ingress/mutable-publishing-scope.md
Labels: lgtm, approved, lifecycle/stale

#867 Move PAO to OCP enhancement
  enhancements/node-tuning/pao-in-nto.md
Labels: lgtm, approved, priority/important-soon
