Repository openshift/enhancements, pull requests merged in 2021-09, with the labels that each got.

#882 enhancements/update/eus-upgrades-mvp: Link upstream skew policy
  enhancements/update/eus-upgrades-mvp.md
Labels: lgtm, approved

#706 apply user defined tags to all resources
  enhancements/api-review/custom-tags-aws.md
Labels: lgtm, approved, priority/important-soon

#885 this-week: 2021-09-03
  this-week/2021-09-03.md
Labels: lgtm, approved

#844 host-port-registry: add 9446 port
  dev-guide/host-port-registry.md
Labels: lgtm, approved

#886 update staff engineers listed in the owners file
  OWNERS
Labels: lgtm, approved

#888 update apiVersion to v1 in enhancement docs
  enhancements/kube-apiserver/audit-policy.md
Labels: lgtm, approved

#884 update warning for None policy for dynamic audit policy
  enhancements/kube-apiserver/audit-policy.md
Labels: lgtm, approved

#889 OWNERS: add tech lead s-urbaniak
  OWNERS
Labels: lgtm, approved

#797 custom routes: set up an explicit trust to the oauth-server
  enhancements/ingress/custom-route-configuration.md
Labels: lgtm, approved

#878 Bug 1987137: Explain profile annotation requirements
  dev-guide/cluster-version-operator/dev/object-deletion.md
  dev-guide/cluster-version-operator/dev/operators.md
Labels: lgtm, approved

#891 Adding OTA Team lead Lalatendu Mohanty
  OWNERS
Labels: lgtm, approved

#896 this-week: 2021-09-10
  this-week/2021-09-10.md
Labels: lgtm, approved

#821 enhancements/update/targeted-update-edge-blocking: Propose a new enhancement
  enhancements/update/targeted-update-edge-blocking.md
Labels: lgtm, approved, priority/important-soon

#898 OWNERS: Prune crawford
  OWNERS
  dev-guide/cluster-version-operator/OWNERS
Labels: lgtm, approved

#901 BUILD-348: update shared resource via CSI Driver proposal
  enhancements/cluster-scope-secret-volumes/csi-driver-host-injections.md
Labels: lgtm, approved

#892 document PR life-cycle timeouts
  README.md
Labels: lgtm, approved, priority/important-soon

#810 tools: update make dependency to build lint image
  Makefile
Labels: lgtm, approved, lifecycle/rotten

#906 tools: adjust the report tool after changing life-cycle timeouts
  tools/cmd/report.go
  tools/stats/stats.go
Labels: lgtm, approved

#849 NE-310 Enhancement proposal for HSTS route admission plugin
  enhancements/ingress/global-admission-hsts.md
Labels: lgtm, approved

#911 this-week: 2021-09-24
  this-week/2021-09-24.md
Labels: lgtm, approved

#910 enhancements/update/targeted-update-edge-blocking: Update after API landed
  enhancements/update/targeted-update-edge-blocking.md
Labels: lgtm, approved

#841 Remove Jenkins from the OCP Payload
  enhancements/builds/remove-jenkins-payload.md
Labels: lgtm, approved

#897 enhancements: Update monitoring alerting consistency proposal
  enhancements/monitoring/alerting-consistency.md
Labels: lgtm, approved

#870 Versioning cincinnati api and json schema
  enhancements/update/versioning-cincinnati-api.md
Labels: lgtm, approved
