Repository openshift/enhancements, pull requests merged in 2021-07, with the labels that each got.

#813 Update ExternalDNS Operator Enhancement
  enhancements/dns/externaldns-operator.md
Labels: approved, lgtm

#820 CONSOLE-2904: Update Console dynamic plugins feature page
  enhancements/console/dynamic-plugins.md
Labels: approved, lgtm

#822 this-week: 2021-07-02
  this-week/2021-07-02.md
Labels: approved, lgtm

#814 this-week: 2021-06-25
  this-week/2021-06-25.md
Labels: approved, lgtm

#701 metrics scraping with local authentication and authorization
  enhancements/monitoring/client-cert-scraping.md
Labels: approved

#793 authentication: describe group syncing for OIDC identity providers
  enhancements/authentication/synchronizing-user-groups-on-login.md
Labels: approved, lgtm

#690 Add repositoryMirrors spec to ImageContentSourcePolicy
  enhancements/api-review/add-repositoryMirrors-spec.md
Labels: approved, lgtm

#829 this-week: 2021-07-09
  this-week/2021-07-09.md
Labels: approved, lgtm

#824 auth: add sur and stlaz to group sync approvers
  enhancements/authentication/synchronizing-user-groups-on-login.md
Labels: approved, lgtm

#823 Remove tenant configuration from loki output configuration.
  enhancements/cluster-logging/forward-to-loki.md
Labels: approved, lgtm

#709 Add proposal for credentials management outside the openshift cluster for new platforms
  enhancements/installer/credentials-management-outside-openshift-cluster.md
Labels: approved, lgtm

#463 Describing steps to support out-of-tree providers
  enhancements/machine-api/out-of-tree-provider-support.md
Labels: approved, lgtm, priority/important-soon

#749 NE-310 Enhancement proposal for HSTS route admission plugin
  enhancements/ingress/global-admission-hsts.md
  enhancements/ingress/global-options-enable-hsts.md
Labels: approved, lgtm

#839 this-week: 2021-07-16
  this-week/2021-07-16.md
Labels: approved, lgtm

#460 ingress: Add empty-requests-policy enhancement
  enhancements/ingress/empty-requests-policy.md
Labels: approved, lgtm

#816 Ingress: Add API for configuring ingress connection timeouts
  enhancements/ingress/request-timeout-configuration.md
Labels: approved, lgtm

#840 Add mandre to OWNERS
  OWNERS
Labels: approved, lgtm

#800 updates: capture offline discussion on eus-upgrades-mvp
  enhancements/update/eus-upgrades-mvp.md
Labels: approved, lgtm, priority/important-soon

#827 Backport the `pause` feature for MachineHealthChecks
  enhancements/machine-api/machine-health-checking.md
Labels: approved, lgtm

#833 kube-apiserver: Fallback on Failing Revisions of Static Pods
  enhancements/kube-apiserver/startup-monitor.md
Labels: approved, lgtm

#845 this-week: 2021-07-23
  this-week/2021-07-23.md
Labels: approved, lgtm

#846 dev-guide: move host-port-registry out of enhancements directory
  dev-guide/host-port-registry.md
Labels: approved, lgtm

#828 Add admin ack upgrade gate
  enhancements/update/upgrades-blocking-on-ack.md
Labels: approved, lgtm, priority/critical-urgent

#832 handling kube-apiserver disruption
  CONVENTIONS.md
Labels: approved, lgtm, priority/important-soon

#695 move CVO upgrades doc to enhancements
  dev-guide/cluster-version-operator/OWNERS
  dev-guide/cluster-version-operator/dev/clusteroperator.md
  dev-guide/cluster-version-operator/dev/clusterversion.md
  dev-guide/cluster-version-operator/dev/metrics.md
  dev-guide/cluster-version-operator/dev/object-deletion.md
  dev-guide/cluster-version-operator/dev/operators.md
  dev-guide/cluster-version-operator/dev/upgrades.md
  dev-guide/cluster-version-operator/user/reconciliation.md
  dev-guide/cluster-version-operator/user/status.md
  dev-guide/cluster-version-operator/user/update-workflow.md
Labels: approved, lgtm

#826 Creating initial skeleton of eo v2 api proposal
  enhancements/cluster-logging/elasticsearch-v2-api-and-infrastructure.md
Labels: approved, lgtm

#847 Add CCM related ports to port registry
  dev-guide/host-port-registry.md
Labels: approved, lgtm

#815 CONSOLE-2425: Support localization of dynamic plugins
  enhancements/console/dynamic-plugins.md
Labels: approved, lgtm

#852 this-week: 2021-07-30
  this-week/2021-07-30.md
Labels: approved, lgtm

#853 Update OWNERS: add rvanderp3
  OWNERS
Labels: approved, lgtm

#707 Add Enhancement for Installing to Alibaba Cloud
  enhancements/installer/alibaba-cloud-ipi.md
  enhancements/installer/alibaba_cloud_install_ipi.png
Labels: approved, lgtm, ok-to-test
