Repository openshift/enhancements, pull requests merged in 2022-10, with the labels that each got.

#1240 STOR-828: CSI Inline Ephemeral Volume Security
  enhancements/storage/csi-inline-vol-security.md
Labels: lgtm, approved

#1237 Add MicroShift Default CSI Plugin proposal
  enhancements/microshift/microshift-default-csi-plugin.md
Labels: lgtm, approved, tide/merge-method-squash, priority/important-soon

#918 vsphere: add multiple datacenter and clusters
  enhancements/installer/vsphere-ipi-zonal.md
Labels: lgtm, approved, priority/important-soon

#1134 installer: adding gcp-ipi-shared-vpc
  enhancements/installer/gcp-ipi-shared-vpc.md
Labels: lgtm, approved

#1256 this-week: 2022-10-07
  this-week/2022-10-07.md
Labels: lgtm, approved

#1252 Clean up host-port-registry for the Metal team
  dev-guide/host-port-registry.md
Labels: lgtm, approved

#1261 update to release.openshift.io/feature-set to match OCP 4.12
  enhancements/installer/component-selection.md
  enhancements/olm/platform-operators.md
Labels: lgtm, approved

#1264 Fix lvmd field typecase
  enhancements/microshift/microshift-default-csi-plugin.md
Labels: lgtm, approved

#1265 this-week: 2022-10-14
  this-week/2022-10-14.md
Labels: lgtm, approved

#1225 Add enhancement for topology configuration
  enhancements/storage/csi-vsphere-operator.md
Labels: lgtm, approved, lifecycle/stale

#1251 enhancements/update/update-blocker-lifecycle: Prioritize critical questions
  enhancements/update/update-blocker-lifecycle/README.md
Labels: lgtm, approved

#1148 This proposal describes how we would add a new field to the install-config during installation to set the load balancer type in AWS either to NLB or ELB.
  enhancements/installer/aws-load-balancer-type.md
Labels: lgtm, approved

#1198 VDPA enhancement
  enhancements/network/vdpa/vdpa-architecture.png
  enhancements/network/vdpa/vdpa-support-overview.md
  enhancements/network/vdpa/virtio-vdpa-ovn-hw-offload.md
Labels: lgtm, approved, ok-to-test

#1262 enhancements/olm: Minor updates to the platform operators proposal
  enhancements/olm/platform-operators.md
Labels: lgtm, approved

#1250 Update ClusterOperator developer guide to document status.relatedObjects
  dev-guide/cluster-version-operator/dev/clusteroperator.md
Labels: lgtm, approved

#1270 OCPCLOUD-1674: Control Plane Machine Set update install flow
  enhancements/machine-api/control-plane-machine-set.md
Labels: lgtm, approved

#1266 dev-guide/cluster-version-operator/dev/clusteroperator: Doc happy-condition reason/message
  dev-guide/cluster-version-operator/dev/clusteroperator.md
Labels: lgtm, approved

#1269 dev-guide/cluster-version-operator/OWNERS: Add Petr
  dev-guide/cluster-version-operator/OWNERS
Labels: lgtm, approved

#1271 Describe how to use annotation rules to skip tests that fail w/ when caps are disabled
  enhancements/installer/component-selection.md
Labels: lgtm, approved

#1274 this-week: 2022-10-28
  this-week/2022-10-28.md
Labels: lgtm, approved

#1158 Stateless Ingress node firewall support using eBPF proposal
  enhancements/network/ingress-node/ebpf-packet-flow.png
  enhancements/network/ingress-node/ingress-node-firewall-with-ebpf.md
  enhancements/network/ingress-node/ingress-nodefw-config-flow.png
Labels: lgtm, approved
