Repository openshift/enhancements, pull requests merged in 2022-04, with the labels that each got.

#1079 this-week: 2022-04-01
  this-week/2022-04-01.md
Labels: lgtm, approved

#1051 Update enhancement proposal to support update of user-defined AWS tags
  enhancements/api-review/custom-tags-aws.md
Labels: lgtm, approved, tide/merge-method-squash, ok-to-test

#1069 Add notes to explain how API fields should be documented in conventions
  CONVENTIONS.md
  dev-guide/api-conventions.md
Labels: lgtm, approved

#1056 BUILD-406: shared resource validating admission EP
  enhancements/cluster-scope-secret-volumes/shared-resource-validation.md
Labels: lgtm, approved

#1034 Agent Installer Development Environment
  enhancements/agent-installer/development-environment.md
Labels: lgtm, approved

#937 monitoring: support configuration of alerting notifications by application owners
  enhancements/monitoring/multi-tenant-alerting.md
Labels: lgtm, approved

#919 Multi-Container-Structured-Logging
  enhancements/cluster-logging/multi-container-structured-logging.md
Labels: lgtm, approved, lifecycle/rotten

#1082 dev-guide/cluster-version-operator/dev/operators: Link capabilities enhancement
  dev-guide/cluster-version-operator/dev/operators.md
Labels: lgtm, approved

#943 [OCPCLOUD-1244] Add proposal for etcd protection mechanism during control plane scaling
  enhancements/etcd/protecting-etcd-quorum-during-control-plane-scaling.md
Labels: lgtm, approved

#1085 this-week: 2022-04-08
  this-week/2022-04-08.md
Labels: lgtm, approved

#1086 tools: add tracking links to weekly report
  tools/Makefile
  tools/enhancements/metadata.go
  tools/enhancements/metadata_test.go
  tools/enhancements/summary.go
  tools/report/report.go
Labels: lgtm, approved

#461 ingress: Add aws-elb-idle-timeout enhancement
  enhancements/ingress/aws-elb-idle-timeout.md
Labels: lgtm, approved

#1088 Add link to redhat support policy for tech preview
  guidelines/techpreview.md
Labels: lgtm, approved

#1075 [OCPCLOUD-1436] AWS IMDSv2 support in MAPI and Installer config
  enhancements/machine-api/aws-imds-v2-support.md
Labels: lgtm, approved

#1061 Host port registry: Add konnectivity agent
  dev-guide/host-port-registry.md
Labels: lgtm, approved, lifecycle/stale

#1048 Dual Stack VIPs for on-prem deployments
  enhancements/network/on-prem-dual-stack-vips.md
Labels: lgtm, approved

#1087 tools: add metadata linting step to linter job
  enhancements/single-node/single-node-openshift-with-workers.md
  guidelines/enhancement_template.md
  hack/Dockerfile.markdownlint
  hack/markdownlint.sh
  hack/metadata-lint.sh
  tools/cmd/annualSummary.go
  tools/cmd/metadataLint.go
  tools/cmd/pullRequests.go
  tools/cmd/report.go
  tools/cmd/reviewers.go
  tools/cmd/root.go
  tools/cmd/show-pr.go
  tools/enhancements/metadata.go
  tools/enhancements/metadata_test.go
Labels: lgtm, approved

#1092 Correct description of cap separation character
  enhancements/installer/component-selection.md
Labels: approved

#1091 tunable-router-kubelet-probes: Fix heading
  enhancements/ingress/tunable-router-kubelet-probes.md
Labels: lgtm, approved

#1094 dev-guide/operators.md: fix links to CVO documentation
  dev-guide/operators.md
Labels: lgtm, approved

#1095 tools: fix linter handling of deleted and renamed files
  hack/find_changed.sh
  hack/metadata-lint.sh
  hack/template-lint.sh
Labels: lgtm, approved

#1096 this-week: 2022-04-22
  this-week/2022-04-22.md
Labels: lgtm, approved

#1093 enhancements/update/update-blocker-lifecycle: Pivot to "update recommendations"
  enhancements/update/update-blocker-lifecycle/README.md
Labels: lgtm, approved

#1023 NE-881: ingress: Add route-subdomain enhancement
  enhancements/ingress/route-subdomain.md
Labels: lgtm, approved

#1035 Pods Egress DSCP QoS proposal
  enhancements/network/egress-qos.md
Labels: lgtm, approved

#1097 Move drawbacks section up to a place of prominence, rework a few other section orderings
  guidelines/enhancement_template.md
Labels: lgtm, approved

#1100 linter improvements
  hack/markdownlint.sh
  hack/metadata-lint.sh
Labels: lgtm, approved
