Repository openshift/enhancements, pull requests merged in 2022-07, with the labels that each got.

#1168 Add monitoring enhacement for HyperShift
  enhancements/hypershift/monitoring.md
Labels: lgtm, approved

#1152 Add enhancement change for disabling SC creation
  enhancements/storage/csi-driver-install.md
Labels: lgtm, approved

#1149 [CFE-508] As a developer I want to update enhancement to support AWS user tag GA
  enhancements/api-review/custom-tags-aws.md
Labels: lgtm, approved, tide/merge-method-squash

#1171 Hypershift networking: Add oauth server and detail socks5 proxy
  enhancements/hypershift/networking/networking.md
Labels: lgtm, approved

#1174 enhancements/installer/component-selection: Suggest early annotation presubmits
  enhancements/installer/component-selection.md
Labels: lgtm, approved

#1178 this-week: 2022-07-08
  this-week/2022-07-08.md
Labels: lgtm, approved

#1185 Insights recommendations as alerts - minor update
  enhancements/insights/prometheus-alerts-for-insights-recommendations.md
Labels: lgtm, approved

#1190 this-week: 2022-07-15
  this-week/2022-07-15.md
Labels: lgtm, approved

#1172 owners: Remove selansen
  OWNERS
Labels: lgtm, approved

#1014 Heterogeneous architecture clusters
  enhancements/multi-arch/heterogeneous-architecture-clusters.md
  enhancements/multi-arch/heterogeneous-cluster.png
Labels: lgtm, approved

#1194 this-week: 2022-07-22
  this-week/2022-07-22.md
Labels: lgtm, approved

#1192 Add links to TRT team aggregator presentation
  enhancements/release/improving-ci-signal.md
Labels: lgtm, approved

#1187 kubernetes for device edge
  enhancements/microshift/kubernetes-for-device-edge.md
Labels: lgtm, approved, priority/important-soon

#1199 tools: fix issues with markdown lint job by pinning dependencies
  Makefile
  hack/Dockerfile.markdownlint
  hack/install-markdownlint.sh
Labels: lgtm, approved

#1159 Bug 2088606: Update DNS-over-TLS proposal
  enhancements/dns/forward-dns-over-tls.md
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-low

#1201 this-week: 2022-07-29
  this-week/2022-07-29.md
Labels: lgtm, approved
