Repository openshift/enhancements, pull requests merged in 2022-11, with the labels that each got.

#1222 Updates to workloads vs configuration API documentation
  dev-guide/api-conventions.md
Labels: lgtm, approved, lifecycle/stale

#1278 this-week: 2022-11-04
  this-week/2022-11-04.md
Labels: lgtm, approved

#1275 Update CSI user config workflow
  enhancements/microshift/microshift-default-csi-plugin.md
Labels: lgtm, approved

#1259 microshift: update set of included APIs
  enhancements/microshift/kubernetes-for-device-edge.md
Labels: lgtm, approved

#1234 New "External" PlatformType addition proposal
  enhancements/cloud-integration/infrastructure-external-platform-type.md
Labels: lgtm, approved

#1247 Update configurable DNS loadbalancer implementation
  enhancements/ingress/configurable-dns-loadbalancerservice.md
Labels: lgtm, approved

#1282 this-week: 2022-11-11
  this-week/2022-11-11.md
Labels: lgtm, approved

#1189 Installer: check operators for stability
  enhancements/installer/operators-check.md
Labels: lgtm, approved, lifecycle/rotten

#1286 CONSOLE-3333: Update dynamic plugin enhancement proposal with v1 API changes
  enhancements/console/dynamic-plugins.md
Labels: lgtm, approved

#1288 this-week: 2022-11-18
  this-week/2022-11-18.md
Labels: lgtm, approved

#1229 PSAP-742: Enable node tuning of HyperShift hosted nodes via NTO
  enhancements/hypershift/node-tuning.md
Labels: lgtm, approved

#1292 Add Oleg Bulatov as Image Registry Team Lead
  OWNERS
Labels: lgtm, approved

#1293 Add enhancement-tool to .gitignore
  .gitignore
Labels: lgtm, approved
