Repository openshift/enhancements, pull requests merged in 2022-08, with the labels that each got.

#1195 Add state of the world enhancement for hypershift Node lifecycle
  enhancements/hypershift/node-lifecycle.md
Labels: lgtm, approved, priority/important-soon

#1180 Update ibm-cloud-provider-for-power-vs-platform to Include Persistent Storage implementation
  enhancements/installer/ibm-cloud-for-power-vs-ipi.md
Labels: lgtm, approved

#1102 Dual stack VIPs: Add rules for openshift/api fields on upgrades
  enhancements/network/on-prem-dual-stack-vips.md
Labels: lgtm, approved

#1207 drop kube-proxy from microshift
  enhancements/microshift/kubernetes-for-device-edge.md
Labels: lgtm, approved

#1184 NE-978: ingress: Add ReloadInterval Option
  enhancements/ingress/haproxy-reload-interval.md
Labels: lgtm, approved

#1210 this-week: 2022-08-05
  this-week/2022-08-05.md
Labels: lgtm, approved

#1175 [WINC] WMCO: Update container runtime details
  enhancements/windows-containers/windows-machine-config-operator.md
Labels: lgtm, approved

#1170 Add a platform operators (phase 0) proposal
  enhancements/olm/platform-operators.md
Labels: lgtm, approved

#1215 [OCPCLOUD-1518] API Conventions: Booleans are disallowed in OpenShift APIs
  dev-guide/api-conventions.md
Labels: lgtm, approved

#1193 USHIFT-40 Default CNI for MicroShift
  enhancements/microshift/microshift-default-cni.md
Labels: lgtm, approved, priority/important-soon

#1220 this-week: 2022-08-19
  this-week/2022-08-19.md
Labels: lgtm, approved

#1218 [OCPCLOUD-1514] API Conventions: Compare Configuration and Workload APIs
  dev-guide/api-conventions.md
Labels: lgtm, approved

#1107 Update enhancement for aws-load-balancer-operator
  enhancements/ingress/aws-load-balancer-operator.md
Labels: lgtm, approved, tide/merge-method-squash

#1221 MicroShift CNI: fix missing comments
  enhancements/microshift/microshift-default-cni.md
Labels: lgtm, approved

#1216 OCPSE-25: [dev-guide] Cluster Fleet Evaluation
  dev-guide/cluster-fleet-evaluation.md
Labels: lgtm, approved

#1214 [OCPCLOUD-1517] API Conventions: Kube consistency is preferred to cloud consistency
  dev-guide/api-conventions.md
Labels: lgtm, approved

#1223 Hypershift networking: Describe how to use Konnektivity for non-http protocols
  enhancements/hypershift/networking/networking.md
Labels: lgtm, approved

#1150 User experience workflow in OCP CoreOS Layering model and phased approach
  enhancements/ocp-coreos-layering.md
  enhancements/ocp-coreos-layering/buildless_layering_support.svg
  enhancements/ocp-coreos-layering/customer_base_image_build.svg
  enhancements/ocp-coreos-layering/image_rollout.svg
  enhancements/ocp-coreos-layering/ocp-coreos-layering.md
Labels: lgtm, approved

#1226 Hypershift: add updated details to inplace upgrade
  enhancements/hypershift/node-lifecycle.md
Labels: lgtm, approved

#1200 Pods SNAT to LB Service IP proposal
  enhancements/network/service-egress-traffic-steering.md
Labels: lgtm, approved

#1228 this-week: 2022-08-26
  this-week/2022-08-26.md
Labels: lgtm, approved

#1209 Add Egress IP health monitoring port
  dev-guide/host-port-registry.md
Labels: lgtm, approved
