Repository openshift/enhancements, pull requests merged in 2022-05, with the labels that each got.

#1081 Change wording in SNO+Workers Operational Aspects of API Extensions section
  enhancements/single-node/single-node-openshift-with-workers.md
Labels: lgtm, approved

#1067 Automated Workflow for Agent-based Installer
  enhancements/agent-installer/automated-workflow-for-agent-based-installer.md
Labels: lgtm, approved, tide/merge-method-squash, priority/important-soon

#1105 Updates link to cluster high availability mode document
  CONVENTIONS.md
Labels: lgtm, approved

#1090 add workflow description section to the template
  guidelines/enhancement_template.md
Labels: lgtm, approved

#1113 this-week: 2022-05-06
  this-week/2022-05-06.md
Labels: lgtm, approved

#1089 Update flow-control-api.md - inline rate limits.
  enhancements/cluster-logging/flow-control-api.md
Labels: lgtm, approved

#1084 enhancement/ingress: add max connections tuning
  enhancements/ingress/haproxy-max-connections-tuning.md
Labels: lgtm, approved

#1054 NE-585 Update enhancement after implementation
  enhancements/ingress/haproxy-healthcheckinterval.md
Labels: lgtm, approved

#1076 Add on-prem internal loadbalancer ports to host port registry
  dev-guide/host-port-registry.md
Labels: lgtm, approved

#1059 Converge ZTP and Metal3 flows
  enhancements/baremetal/ztp-metal3.md
Labels: lgtm, approved

#1109 enhancements/installer/component-selection: Catch up with landed API
  enhancements/installer/component-selection.md
Labels: lgtm, approved

#1010 authentication: add enhancement on PSa autolabeling
  enhancements/authentication/pod-security-admission-autolabeling.md
Labels: lgtm, approved

#1108 Remove the references of workerlatencyprofile status
  enhancements/worker-latency-profile/worker-latency-profile.md
Labels: lgtm, approved

#1116 lint: only apply template lint rules to new files
  hack/find_new.sh
  hack/metadata-lint.sh
  hack/template-lint.sh
Labels: lgtm, approved

#1112 Update Windows containerd design details
  enhancements/windows-containers/container-runtime-containerd.md
Labels: lgtm

#1111 fix a note about SC alerts in csi-migration enhancement
  enhancements/storage/csi-migration.md
Labels: lgtm, approved

#1117 lint: only apply metadata lint rules to new files
  hack/metadata-lint.sh
Labels: lgtm, approved

#1118 enhancements/machine-api/azure-ultra-disks: update api
  enhancements/machine-api/azure-ultra-disks.md
Labels: lgtm, approved

#1008 [OCPCLOUD-1248] Add initial iteration of ControlPlaneMachineSet operator enhancement
  enhancements/machine-api/control-plane-machine-set.md
Labels: lgtm, approved

#1119 this-week: 2022-05-13
  this-week/2022-05-13.md
Labels: lgtm, approved

#1071 baremetal: Add bootstrap-external-ip
  enhancements/baremetal/bootstrap-external-ip.md
Labels: lgtm, approved

#1122 template: update instructions for milestones
  guidelines/enhancement_template.md
Labels: lgtm, approved

#1009 OpenStack Cloud Provider Config Upgrade
  enhancements/cloud-integration/openstack/cloud-provider-config-upgrade.md
Labels: lgtm, approved

#1128 owners: add jupierce as a staff engineer
  OWNERS
Labels: lgtm, approved

#987 Add the DNS-over-TLS enhancement initial draft
  enhancements/dns/forward-dns-over-tls.md
Labels: lgtm, approved

#1115 fix Power VS install-config example
  enhancements/installer/ibm-cloud-for-power-vs-ipi.md
Labels: lgtm, approved

#1132 pod-security-admission: clarify final restricted profile goal
  enhancements/authentication/pod-security-admission.md
Labels: lgtm, approved

#1030 enhancements/monitoring: User-Defined Alerting and Relabeling Rules
  enhancements/monitoring/alert-overrides.md
Labels: lgtm, approved

#1123 CONSOLE-3159: API changes for i18n
  enhancements/console/dynamic-plugins.md
Labels: lgtm, approved

#1120 Insights: cluster transfer minor update
  enhancements/insights/pulling-pull-secret-from-ocm.md
Labels: lgtm, approved

#1037 New Insights config API proposal
  enhancements/insights/insights-config-api.md
Labels: lgtm, approved

#1136 this-week: 2022-05-27
  this-week/2022-05-27.md
  tools/enhancements/summary.go
  tools/stats/stats.go
Labels: lgtm, approved

#1140 Clean up language in improving ci signal doc
  enhancements/release/improving-ci-signal.md
Labels: lgtm, approved
