Repository openshift/enhancements, pull requests merged in 2022-02, with the labels that each got.

#1018 Add Windows Health Management containerd context
  enhancements/windows-containers/health-management.md
Labels: lgtm, approved

#1024 Change openshift-managed to OpenShift managed
  enhancements/windows-containers/health-management.md
Labels: lgtm, approved

#924 CLI Manager
  enhancements/oc/cli-manager.md
Labels: lgtm, approved

#955 Enhancement for OAuth2 Authorization Grant Login for oc
  enhancements/authentication/improved-login-workflow.md
Labels: lgtm, approved

#1026 this-week: 2022-02-04
  this-week/2022-02-04.md
Labels: lgtm, approved

#1031 tools: add annual-summary --year option
  tools/cmd/annualSummary.go
Labels: lgtm, approved

#1021 [OCPCLOUD-1377] Add "Azure Ultra Disks support in Machine API" enhancement
  enhancements/machine-api/azure-ultra-disks.md
Labels: lgtm, approved

#1033 this-week: 2022-02-11
  this-week/2022-02-11.md
Labels: lgtm, approved

#1020 Add enhancement for AWS Load Balancer operator
  enhancements/ingress/aws-load-balancer-operator.md
Labels: lgtm, approved, tide/merge-method-squash

#1017 helm: fix example in the documentation
  enhancements/helm3/console.md
  enhancements/helm3/namespace-scoped-helm-repository-crd.md
Labels: lgtm, approved

#931 NE-367: Add logLevel and operatorLogLevel APIs for DNS
  enhancements/dns/dns-operator-operand-logging-level.md
Labels: lgtm, approved

#1040 Revert "Enhancement for enabling single-node-openshift with workers"
  enhancements/single-node/single-node-openshift-with-workers.md
Labels: lgtm, approved

#1038 Refine how a resource specifies multiple capabilities
  enhancements/installer/component-selection.md
Labels: lgtm, approved

#1042 Change cap annotation delimiter to +
  enhancements/installer/component-selection.md
Labels: lgtm, approved

#1043 Drop incorrect statement about handling cluster profile resources
  enhancements/installer/component-selection.md
Labels: lgtm, approved

#1000 Update enhancement proposal to support update of user-defined AWS tags
  enhancements/api-review/custom-tags-aws.md
Labels: lgtm, approved, tide/merge-method-squash, ok-to-test

#1045 this-week: 2022-02-25
  this-week/2022-02-25.md
Labels: lgtm, approved

#1029 OVN-Kubernetes on Hypershift
  enhancements/network/ovn-on-hypershift.md
Labels: lgtm, approved, priority/important-soon
