Repository openshift/enhancements, pull requests merged in 2022-06, with the labels that each got.

#1143 this-week: 2022-06-03
  this-week/2022-06-03.md
Labels: lgtm, approved

#1144 Move out of tree cloud provider prop to cloud-integration folder
  enhancements/cloud-integration/out-of-tree-provider-support.md
Labels: lgtm, approved

#1103 Update improving CI signal enhancement to reflect current practices
  enhancements/release/improving-ci-signal.md
Labels: lgtm, approved

#1141 MGMT-10403: SNO + Workers enhancement - adjust upgrade non-goal to be a goal
  enhancements/single-node/single-node-openshift-with-workers.md
Labels: lgtm, approved

#1151 this-week: 2022-06-10
  this-week/2022-06-10.md
Labels: lgtm, approved

#981 Added proposal for HyperShift monitoring.
  enhancements/monitoring/assets/hypershift-alternative.png
  enhancements/monitoring/assets/hypershift-chall.png
  enhancements/monitoring/assets/hypershift-cmo.png
  enhancements/monitoring/assets/hypershift-cus.png
  enhancements/monitoring/assets/hypershift-details.png
  enhancements/monitoring/assets/hypershift-highlvl.png
  enhancements/monitoring/hypershift-monitoring.md
Labels: lgtm, approved, tide/merge-method-squash

#1125 AGENT-40: Enhancement for generating admin kubeconfig
  enhancements/agent-installer/automated-workflow-kubeconfig.md
  enhancements/agent-installer/kubeconfig_implications_with_cert_loading.svg
  enhancements/agent-installer/kubeconfig_implications_without_changes.svg
Labels: lgtm, approved, priority/important-soon

#1127 Proposal for hiding container mountpoints from systemd
  enhancements/hide-container-mountpoints.md
Labels: lgtm, approved

#1160 Clarified documentation expectations for hide-container-mountpoints enhancement
  enhancements/hide-container-mountpoints.md
Labels: lgtm, approved

#1145 enh/auth/login-logout-events:update implementation
  enhancements/authentication/login-logout-events.md
Labels: lgtm, approved

#1066 Document the various event files produced by CI
  dev-guide/ci/events-files.md
Labels: lgtm, approved, lifecycle/stale

#1162 this-week: 2022-06-24
  this-week/2022-06-24.md
Labels: lgtm, approved

#1153 Enhancement to refine ClusterVersion history pruning
  enhancements/update/clusterversion-history-pruning.md
Labels: lgtm, approved

#1147 Follow up migirate from icsp to idms
  enhancements/api-review/add-new-CRD-ImageDigestMirrorSet-and-ImageTagMirrorSet-to-config.openshift.io.md
Labels: lgtm, approved
