Repository openshift/enhancements, pull requests merged in 2023-03, with the labels that each got.

#1316 NP-604: Add MicroShift Service of Loadbalancer Type Support
  enhancements/microshift/loadbalancer-service-support.md
Labels: lgtm, approved, priority/important-soon, jira/valid-reference

#1362 this-week: 2023-03-03
  this-week/2023-03-03.md
Labels: lgtm, approved

#1361 ETCD-356: Supportability of etcd in MicroShift
  enhancements/microshift/etcd-supportability.md
Labels: lgtm, approved, jira/valid-reference

#1350 ETCD-391: Adding Microshift enhancement for defragementation of etcd
  enhancements/microshift/periodic-etcd-defragmentation-in-microshift.md
Labels: lgtm, approved, priority/important-soon, jira/valid-reference

#1364 this-week: 2023-03-10
  this-week/2023-03-10.md
Labels: lgtm, approved

#1366 MicroShift: update apiserver certificates configuration + networking
  enhancements/microshift/microshift-apiserver-certs.md
Labels: lgtm, approved

#1360 WINC-939: Windows Node Global Egress Proxy Support
  enhancements/windows-containers/windows-node-egress-proxy.md
Labels: lgtm, approved, jira/valid-reference

#1347 ingress: Updated gateway-api with details on ReferenceGrants
  enhancements/ingress/gateway-api-with-cluster-ingress-operator.md
Labels: lgtm, approved

#1371 this-week: 2023-03-24
  hack/this-week.sh
  this-week/2023-03-24.md
Labels: lgtm, approved

#1279 on demand Insights data gathering
  enhancements/insights/on-demand gathering diagram.png
  enhancements/insights/on-demand-data-gathering.md
Labels: lgtm, approved

#1310 AGENT-436: Propose interactive network config for agent-based installer
  enhancements/agent-installer/interactive-network-config.md
Labels: lgtm, approved

#1375 this-week: 2023-03-31
  this-week/2023-03-31.md
Labels: lgtm, approved

#1338 [SDN-2481] Enhancement proposal to migrate Multiple External Gateways to use a CRD
  enhancements/network/ovn-kubernetes-multiple-external-gateway.md
Labels: lgtm, approved
