Repository openshift/enhancements, pull requests merged in 2023-09, with the labels that each got.

#1469 this-week: 2023-09-01
  this-week/2023-09-01.md
Labels: lgtm, approved

#1307 CFE-815: Route secret injection for external certificate management
  enhancements/ingress/route-secret-injection-for-external-certificate-management.md
Labels: lgtm, approved, jira/valid-reference

#1472 this-week: 2023-09-08
  this-week/2023-09-08.md
Labels: lgtm, approved

#1335 CFE-748: Improve CoreDNS Integration with EgressFirewall
  enhancements/dns/coredns-egressfirewall-integration.md
  enhancements/dns/coredns-egressfirewall-integration.png
Labels: lgtm, approved, jira/valid-reference

#1443 Add implementation details to tokenized auth
  enhancements/cloud-integration/tokenized-auth-enablement-operators-on-cloud.md
Labels: lgtm, approved

#1476 this-week: 2023-09-15
  this-week/2023-09-15.md
Labels: lgtm, approved

#1475 csi-proxy upgrade procedure updates
  enhancements/windows-containers/csi-proxy.md
Labels: lgtm, approved

#1470 storage: mark ebs-operator.md as replaced
  enhancements/storage/csi-driver-install.md
  enhancements/storage/csi-ebs-operator.md
Labels: lgtm, approved

#1477 ICSP to IDMS update the implementation migration path
  enhancements/api-review/add-new-CRD-ImageDigestMirrorSet-and-ImageTagMirrorSet-to-config.openshift.io.md
Labels: lgtm, approved

#1484 this-week: 2023-09-22
  this-week/2023-09-22.md
Labels: lgtm, approved

#1473 dev-guide/host-port-registry: Add process and control-plane only columns
  dev-guide/host-port-registry.md
Labels: lgtm, approved

#1395 Support BMC CA Certificate
  enhancements/security/bmc-ca-certificate-support.md
Labels: lgtm, approved, ok-to-test
