Repository openshift/enhancements, pull requests merged in 2023-06, with the labels that each got.

#1416 this-week: 2023-06-02
  hack/install-markdownlint.sh
  this-week/2023-06-02.md
Labels: lgtm, approved

#1418 CFE-862 : Update Azure user-defined tags EP with GA details
  enhancements/api-review/azure_user_defined_tags.md
Labels: lgtm, approved

#1420 enhancements/update/targeted-update-edge-blocking: Drop Evaluating
  enhancements/update/targeted-update-edge-blocking.md
Labels: lgtm, approved

#1422 this-week: 2023-06-09
  this-week/2023-06-09.md
Labels: lgtm, approved

#1399 OpenShift API Conventions: no annotations convention
  dev-guide/api-conventions.md
Labels: lgtm, approved

#1339 Tokenized Cloud Auth Enablement For Operators
  enhancements/cloud-integration/STS_tomorrow.jpg
  enhancements/cloud-integration/tokenized-auth-enablement-operators-on-cloud.md
Labels: lgtm, approved, tide/merge-method-squash

#1425 this-week: 2023-06-16
  this-week/2023-06-16.md
Labels: lgtm, approved

#1232 installer-aws: create edge compute pool for AWS Local Zones
  enhancements/installer/aws-custom-edge-local-wavelength-zones-diagram.png
  enhancements/installer/aws-custom-edge-machineset-local-zones.md
Labels: lgtm, approved

#1428 Clarify that enabling upstream alpha features need staff-eng approval
  guidelines/supportability.md
Labels: lgtm, approved

#1406 USHIFT 1104 - MicroShift CSI Snapshotting Integration
  enhancements/microshift/microshift-csi-snapshot-integration.md
Labels: lgtm, approved, tide/merge-method-squash

#1430 this-week: 2023-06-23
  Makefile
  this-week/2023-06-23.md
  tools/Makefile
  tools/cmd/annualSummary.go
  tools/cmd/closedStale.go
  tools/cmd/metadataLint.go
  tools/cmd/pullRequests.go
  tools/cmd/report.go
  tools/cmd/reviewers.go
  tools/cmd/root.go
  tools/cmd/show-pr.go
  tools/config/jira.go
  tools/enhancements/metadata.go
  tools/enhancements/summary.go
  tools/go.mod
  tools/go.sum
  tools/reviewers/reviewers.go
  tools/stats/stats.go
  tools/util/query.go
Labels: lgtm, approved

#1378 OCPCLOUD-2011: Update implementation history of External platform type EP
  enhancements/cloud-integration/infrastructure-external-platform-type.md
Labels: lgtm, approved, jira/valid-reference

#1397 Installer: AWS Shared VPC
  enhancements/installer/aws-cross-account-dns-zone.md
  enhancements/installer/aws_shared_vpc.png
Labels: lgtm, approved

#1433 this-week: 2023-06-30
  this-week/2023-06-30.md
Labels: lgtm, approved

#1359 console: additional updates for dynamic plugin GA
  enhancements/console/dynamic-plugins.md
Labels: lgtm, approved

#1434 update owners list
  OWNERS
  tools/cmd/ownerNames.go
Labels: lgtm, approved

#1435 add joepvd for the art team
  OWNERS
Labels: lgtm, approved
