Repository openshift/enhancements, pull requests merged in 2023-07, with the labels that each got.

#1437 Fix broken link
  enhancements/cluster-logging/hypershift-audit-logs.md
Labels: lgtm, approved

#1291 Improved platform tests
  enhancements/testing/extended-platform-tests.md
  enhancements/testing/improved-platform-tests.md
  enhancements/testing/new-flow.png
  enhancements/testing/old-flow.png
Labels: lgtm, approved, tide/merge-method-squash

#1324 Bug 1943194: update cluster-autoscaler-operator enhancement
  enhancements/machine-api/cluster-autoscaler-operator.md
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-medium

#1419 cluster-logging: Fine grained logs access
  enhancements/cluster-logging/fine-grained-per-namespace-logs-access.md
  enhancements/cluster-logging/images/authz-flow.png
Labels: lgtm, approved

#1429 ODC-7331: New ConsoleSample CRD proposal
  enhancements/console/samples-add-page.png
  enhancements/console/samples-import-git.png
  enhancements/console/samples.md
  enhancements/console/samples.png
Labels: lgtm, approved, jira/valid-reference

#1389 Enable CBO on Azure and GCP platforms
  enhancements/baremetal/enable-baremetal-on-azure-gcp.md
Labels: lgtm, approved

#1410 LOG-1344: Multi clusterlogforwarder proposal
  enhancements/cluster-logging/multi-cluster-log-forwarder.md
Labels: lgtm, approved, jira/valid-reference

#1414 SDN-4004: Admin Network Policy in OVN-K
  enhancements/network/admin-network-policy.md
Labels: lgtm, approved, ¯\_(ツ)_/¯, jira/valid-reference

#1441 this-week: 2023-07-14
  this-week/2023-07-14.md
Labels: lgtm, approved

#1391 AUTH-372: enhancements/authentication: Custom SCC preemption prevention
  enhancements/authentication/custom-scc-preemption-prevention.md
Labels: lgtm, approved, jira/valid-reference

#1296 Enhancement Proposal for Adding HTTP header to HAProxy Without Customizing haproxy.config Template
  enhancements/ingress/set-delete-http-headers.md
Labels: lgtm, approved

#1377 Network: make namespaceSelector a mandatory field for dynamicHops
  enhancements/network/ovn-kubernetes-multiple-external-gateway.md
Labels: lgtm, approved

#1423 STOR-1310: Enhancement for Secrets Store CSI Driver Operator
  enhancements/storage/csi-secrets-store.md
Labels: lgtm, approved, jira/valid-reference

#1355 Update host-port-registry for etcd port 9980
  dev-guide/host-port-registry.md
Labels: lgtm, approved

#1448 this-week: 2023-07-28
  this-week/2023-07-28.md
Labels: lgtm, approved
