Repository openshift/enhancements, pull requests merged in 2023-01, with the labels that each got.

#1308 this-week: 2022 annual summary
  this-week/2022.md
Labels: lgtm, approved

#1309 this-week: 2023-01-06
  this-week/2023-01-06.md
Labels: lgtm, approved

#1300 Update user story guidance in enhancement template
  guidelines/enhancement_template.md
Labels: lgtm, approved

#1317 this-week: 2023-01-13
  this-week/2023-01-13.md
Labels: lgtm, approved

#1315 enhancements/installer/component-selection: Clarify cluster-bot testing
  enhancements/installer/component-selection.md
Labels: lgtm, approved

#1287 dev-guide/api-conventions: Explain preference for single canonical phrasing
  dev-guide/api-conventions.md
Labels: lgtm, approved, lifecycle/stale

#1321 this-week: 2023-01-20
  this-week/2023-01-20.md
Labels: lgtm, approved

#1213 feat: add wide cluster configuration for workload partitioning
  enhancements/workload-partitioning/wide-availability-workload-partitioning.md
Labels: lgtm, approved

#1191 CFE-543 : Apply user defined tags to all Azure resources created by OpenShift
  enhancements/api-review/azure_user_defined_tags.md
Labels: lgtm, approved, tide/merge-method-squash

#1163 Installer: user-encrypted storage keys enhancement
  enhancements/installer/storage-class-encrypted.md
Labels: lgtm, approved

#1242 ETCD-318: Adding MicroShift etcd enhancement
  enhancements/microshift/etcd-as-a-transient-systemd-unit.md
Labels: lgtm, approved, tide/merge-method-squash, priority/important-soon

#1325 this-week: 2023-01-27
  this-week/2023-01-27.md
Labels: lgtm, approved

#1326 upgrades OWNERS: add current OTA team members and remove former ones
  enhancements/update/OWNERS
Labels: lgtm, approved

#1323 OTA-787: enhancements/update/update-blocker-lifecycle: Port from Bugzilla to Jira
  enhancements/update/update-blocker-lifecycle/README.md
Labels: lgtm, approved, jira/valid-reference

#1303 ingress: Add gateway-api enhancement
  enhancements/ingress/gateway-api-with-cluster-ingress-operator.md
Labels: lgtm, approved
