Repository openshift/enhancements, pull requests merged in 2023-04, with the labels that each got.

#1331 CONVENTIONS.md: document requirements for metrics
  CONVENTIONS.md
Labels: lgtm, approved, lifecycle/stale

#1349 NE-1176 Should we have a feature gate?
  enhancements/ingress/gateway-api-with-cluster-ingress-operator.md
Labels: lgtm, approved, tide/merge-method-squash

#1380 this-week: 2023-04-07
  this-week/2023-04-07.md
Labels: lgtm, approved

#1379 Clean up EP guidance docs
  README.md
  ROADMAP.md
  guidelines/README.md
  guidelines/enhancement_template.md
Labels: lgtm, approved

#1381 this-week: 2023-04-14
  this-week/2023-04-14.md
Labels: lgtm, approved

#1295 Additional trusted certificate authorities for image registries
  enhancements/machine-config/certificate-authorities-for-image-registries.md
Labels: lgtm, approved

#1386 this-week: 2023-04-21
  this-week/2023-04-21.md
Labels: lgtm, approved

#1385 feat(hypershift): Priority class override
  enhancements/hypershift/priority-class/priority-class-override.md
Labels: lgtm, approved

#1390 this-week: 2023-04-28
  this-week/2023-04-28.md
Labels: lgtm, approved
