Repository openshift/enhancements, pull requests merged in 2023-08, with the labels that each got.

#1365 OCPBU-199: enhancement proposal for dual-stack support with openstack
  enhancements/network/openstack-dual-stack.md
Labels: lgtm, approved, jira/valid-reference

#1445 USHIFT-1473: feat: retro ep for storage migration
  enhancements/microshift/microshift-storage-version-migrator.md
Labels: lgtm, approved, tide/merge-method-squash, jira/valid-reference

#1451 Update multi ClusterLogForwarder proposal for LogFileMetricsExporter
  enhancements/cluster-logging/multi-cluster-log-forwarder.md
Labels: lgtm, approved

#1452 this-week: 2023-08-04
  this-week/2023-08-04.md
Labels: lgtm, approved

#1217 CFE-544 : Apply user defined labels & tags to all GCP resources created by OpenShift
  enhancements/api-review/gcp_user_defined_labels.md
Labels: lgtm, approved

#1394 NE-1261: Add test plan to enhancement proposal
  enhancements/ingress/gateway-api-with-cluster-ingress-operator.md
Labels: lgtm, approved, jira/valid-reference

#1455 this-week: 2023-08-11
  this-week/2023-08-11.md
Labels: lgtm, approved

#1398 Update flow control API enhancement to match final implementation
  enhancements/cluster-logging/flow-control-api.md
Labels: lgtm, approved

#1417 Support for Multiarch Manager Operator
  enhancements/multi-arch/multiarch-manager-operator.md
Labels: lgtm, approved

#1459 CFE-916: Update TechPreview limitations for GCP tags support
  enhancements/api-review/gcp_user_defined_labels.md
Labels: lgtm, approved, jira/valid-reference

#1460 Include hypershift use case in template
  guidelines/enhancement_template.md
Labels: lgtm, approved

#1462 this-week: 2023-08-25
  this-week/2023-08-25.md
Labels: lgtm, approved

#1464 WINC-1102: Update WICD, node-proxy enhancements
  enhancements/windows-containers/health-management.md
  enhancements/windows-containers/windows-node-egress-proxy.md
Labels: lgtm, approved, jira/valid-reference

#1439 USHIFT-1414: Update MicroShift OSTree updateability post-implementation
  enhancements/microshift/microshift-updateability-ostree.md
Labels: lgtm, approved, jira/valid-reference

#1467 dev-guide/host-port-registry: Declare cluster-version operator metrics on TCP 9099
  dev-guide/host-port-registry.md
Labels: lgtm, approved
