Repository openshift/enhancements, pull requests merged in 2023-10, with the labels that each got.

#1447 ETCD-425: adding etcd tuning profiles enhancement
  enhancements/etcd/etcd-tuning-profiles.md
Labels: lgtm, approved, jira/valid-reference

#1488 Update multi-cluster-log-forwarder.md to correct api spec
  enhancements/cluster-logging/multi-cluster-log-forwarder.md
Labels: lgtm, approved

#1409 Upgrading to 4.14 with OVN IC
  dev-guide/host-port-registry.md
  enhancements/network/upgrades-with-ovn-ic.md
Labels: lgtm, approved

#1489 this-week: 2023-10-06
  this-week/2023-10-06.md
Labels: lgtm, approved

#1461 OCPCLOUD-1910: Installing Cluster API components in OpenShift
  enhancements/cluster-api/assets/current-build-time.png
  enhancements/cluster-api/assets/current-runtime.png
  enhancements/cluster-api/assets/proposed-build-time.png
  enhancements/cluster-api/assets/proposed-runtime.png
  enhancements/cluster-api/installing-cluster-api-components-in-ocp.md
Labels: lgtm, approved, jira/valid-reference

#1412 AUTH-387: auth: add enhancement for unsupported direct kube-apiserver oidc config
  enhancements/authentication/direct-oidc-study/setup_keycloak.sh
  enhancements/authentication/direct-oidc-study/study-oidc-in-openshift.md
  enhancements/authentication/unsupported-direct-use-of-oidc.md
  hack/find_new.sh
  hack/ignore_lib.sh
  hack/lint-ignores
  hack/markdownlint.sh
  hack/metadata-lint.sh
  hack/template-lint.sh
Labels: lgtm, approved, jira/valid-reference

#1471 STOR-1454: merge CSI driver operators
  enhancements/storage/csi-driver-operator-merge.md
Labels: lgtm, approved, jira/valid-reference

#1495 this-week: 2023-10-13
  hack/metadata-lint.sh
  hack/template-lint.sh
  this-week/2023-10-13.md
Labels: lgtm, approved

#1491 Add protocol and control-plane for ovn and sdn ports in host port registry
  dev-guide/host-port-registry.md
Labels: lgtm, approved

#1421 enhancement: Shared and Guaranteed CPU Pools
  enhancements/shared-and-guaranteed-cpu-pools.md
Labels: lgtm, approved

#1486 Automated Backups of Etcd
  enhancements/etcd/automated-backups.md
Labels: lgtm, approved

#1483 Don't require registry during reboot and upgrade
  enhancements/update/dont-require-registry-during-reboot-and-upgrade.md
Labels: lgtm, approved

#1402 [OCPNODE-1639] Add ClusterImagePolicy, ImagePolicy to support signature verification
  enhancements/api-review/add-ClusterImagePolicy-and-ImagePolicy-for-Signature-Verification.md
Labels: lgtm, approved

#1498 this-week: 2023-10-20
  this-week/2023-10-20.md
Labels: lgtm, approved

#1501 OTA-1041: Add some warnings about gotchas that have caused issues for teams doing capability implementations
  enhancements/installer/component-selection.md
Labels: lgtm, approved, jira/valid-reference

#1064 Add enhancement proposal for SDN live migration
  enhancements/network/sdn-live-migration.md
Labels: lgtm, approved

#1504 this-week: 2023-10-27
  this-week/2023-10-27.md
Labels: lgtm, approved

#1507 enhancements/update/targeted-update-edge-blocking: 1s between different PromQL
  enhancements/update/targeted-update-edge-blocking.md
Labels: lgtm, approved

#1444 SPLAT-653: Updates in installer/aws-localzones
  enhancements/installer/aws-custom-edge-machineset-local-zones.md
Labels: lgtm, approved, lifecycle/rotten, jira/valid-reference
