Repository openshift/enhancements, pull requests merged in 2024-05, with the labels that each got.

#1465 OCPCLOUD-1578: Add enhancement for converting Machine API resource to Cluster API
  enhancements/machine-api/converting-machine-api-to-cluster-api.md
Labels: lgtm, approved, jira/valid-reference

#1622 Update ClusterImagePolicy enhancement to match the actual implementation
  enhancements/api-review/add-ClusterImagePolicy-and-ImagePolicy-for-Signature-Verification.md
Labels: lgtm, approved

#1525 MCO-507: admin defined node disruption policy enhancement
  enhancements/machine-config/admin-defined-node-disruption-policy.md
Labels: lgtm, approved, jira/valid-reference

#1549 ETCD-514: Add etcd size tuning
  enhancements/etcd/etcd-size-tuning.md
Labels: lgtm, approved, jira/valid-reference

#1626 Remove dulek from approvers
  OWNERS
Labels: lgtm, approved

#1624 CFE-1038: update command-line argument name for RouteExternalCertificate feature-gate
  enhancements/ingress/route-secret-injection-for-external-certificate-management.md
Labels: lgtm, approved, jira/valid-reference

#1614 Track host port for `sriov-network-metrics-exporter`
  dev-guide/host-port-registry.md
Labels: lgtm, approved

#1528 Bootstrapping Clusters with CAPI Infrastructure Providers
  enhancements/installer/bootstrapping-clusters-with-capi-providers.md
  enhancements/installer/capi_embedded.jpg
  enhancements/installer/terraform_embedded.jpg
Labels: lgtm, approved, lifecycle/rotten

#1521 Enhancement: North-South IPsec support
  enhancements/network/ovn-kubernetes-ns-ipsec.md
Labels: lgtm, approved

#1618 LOG-5428: Add OTLP support to ClusterLogForwarder
  enhancements/cluster-logging/forwarder-to-otlp.md
Labels: lgtm, approved, jira/valid-reference

#1537 LOG-4928: Cluster logging next APIs
  enhancements/cluster-logging/cluster-logging-log-forwarding.md
  enhancements/cluster-logging/logs-observability-openshift-io-apis.md
Labels: lgtm, approved, jira/valid-reference
