Repository openshift/enhancements, pull requests merged in 2024-07, with the labels that each got.

#1651 Update approvers list to yuqi-zhang for MCO
  OWNERS
Labels: lgtm, approved

#1617 MGMT-17600: Add image-based installer enhancement
  enhancements/installer/image-based-installer.md
Labels: lgtm, approved, jira/valid-reference

#1424 Add a continuous Kubernetes rebase proposal
  dev-guide/kubernetes-continuous-rebase.md
Labels: lgtm, approved

#1463 Mutable dual-stack VIPs
  enhancements/network/on-prem-mutable-vips.md
Labels: lgtm, approved

#1641 dev-guide/operators.md: update the CI cluster's domain
  dev-guide/operators.md
Labels: lgtm, approved

#1643 USHIFT-3458: Low Latency Workloads on MicroShift
  enhancements/microshift/low-latency-workloads-on-microshift.md
Labels: lgtm, approved, jira/valid-reference

#1620 OCPEDGE-1147: feat!: init kubesan csi driver integration proposal
  enhancements/local-storage/kubesan-csi-driver-integration-into-lvms.md
Labels: lgtm, approved, jira/valid-reference

#1644 Move steps for migrating code to csi-operator to ocp enhancements
  enhancements/storage/csi-driver-operator-merge.md
Labels: lgtm, approved

#1653 USHIFT-706: Optionally disable LVMS and CSI deployment
  enhancements/microshift/disabling-storage-components.md
Labels: lgtm, approved, jira/valid-reference

#1638 user-defined-network-segmentation: Add CRDs for managing networks
  enhancements/network/user-defined-network-segmentation.md
Labels: lgtm, approved, ok-to-test
