Repository openshift/enhancements, pull requests merged in 2024-01, with the labels that each got.

#1526 Update forwarder-input-selectors.md
  enhancements/cluster-logging/forwarder-input-selectors.md
Labels: lgtm, approved

#1534 this-week: 2024-01-05
  this-week/2024-01-05.md
Labels: lgtm, approved

#1535 convert featuregate FAQ from google doc to part of the dev-guide
  dev-guide/featuresets.md
Labels: lgtm, approved

#1511 Add beta features guidelines
  guidelines/supportability.md
Labels: lgtm, approved

#1536 Add team responsibility to document tier 2 support for beta feature
  guidelines/supportability.md
Labels: lgtm, approved

#1497 LOG-4606: Initial proposal for Azure Monitor Log integration
  enhancements/cluster-logging/forward_to_azure_monitor_logs.md
Labels: lgtm, approved, lifecycle/rotten, jira/valid-reference

#1543 this-week: 2024-01-19
  this-week/2024-01-19.md
Labels: lgtm, approved

#1538 WRKLDS-950: must-gather: add --since and --since-time flags to proposal
  enhancements/oc/must-gather.md
Labels: lgtm, approved, jira/valid-reference

#1544 OWNERS: extend approvers with ingvagabund
  OWNERS
Labels: lgtm, approved

#1547 tests: update command name to reflect reality
  enhancements/testing/improved-platform-tests.md
Labels: lgtm, approved

#1550 this-week: 2024-01-26
  this-week/2024-01-26.md
Labels: lgtm, approved
