Repository openshift/enhancements, pull requests merged in 2024-08, with the labels that each got.

#1636 Adds support for BGP in OVNK
  enhancements/network/bgp-ovn-kubernetes.md
  enhancements/network/images/bgp_novpn_advertisements.png
  enhancements/network/images/vrf-lite.png
Labels: lgtm, approved

#1648 USHIFT-3490: workload partitioning enhancement
  enhancements/microshift/workload-partitioning-in-microshift.md
Labels: lgtm, approved, jira/valid-reference

#1654 update vSphere driver configuration enhancement
  enhancements/storage/vsphere-driver-configuration.md
Labels: lgtm, approved, qe-approved

#1633 OTA-1294: enhancements/security/openshift-image-policy: Propose new enhancement
  enhancements/security/openshift-image-policy.md
Labels: lgtm, approved, jira/valid-reference

#1649 Add enhancement for supporting user namespaces
  enhancements/kubelet/user-namespaces-support.md
Labels: lgtm, approved

#1663 NOJIRA: fix: remove misleading .configurationPolicy=ExternalConfiguration
  enhancements/microshift/lvms-topolvm-downstream-replacement.md
Labels: lgtm, approved
