Repository openshift/enhancements, pull requests merged in 2024-11, with the labels that each got.

#1690 OTA-962: Duration of migration to multi-arch
  dev-guide/cluster-version-operator/dev/clusteroperator.md
  enhancements/update/duration-of-migration-to-multi-arch.md
Labels: lgtm, approved, jira/valid-reference

#1710 Fix last-updated in duration-of-migration-to-multi-arch.md
  enhancements/update/duration-of-migration-to-multi-arch.md
Labels: lgtm, approved

#1706 CONSOLE-4327: Add new API field to ConsolePlugin CRD for allowing additional CSP sources
  enhancements/console/dynamic-plugins.md
Labels: lgtm, approved, jira/valid-reference

#1652 OCPBUGS-34373: routes/custom-host permission update for externalCertificate
  enhancements/ingress/route-secret-injection-for-external-certificate-management.md
Labels: lgtm, approved, jira/valid-bug, jira/severity-important, jira/valid-reference

#1685 USHIFT-4377: introduce microshift ingress performance enhancement
  enhancements/microshift/microshift-router-configuration-performance.md
Labels: lgtm, approved, qe-approved, jira/valid-reference

#1656 STOR-1988: add enhancement for GCP Filestore Operator WIF
  enhancements/storage/gcp-filestore-wif.md
Labels: lgtm, approved, jira/valid-reference

#1704 STOR-2040: oc adm top persistentvolumeclaim
  enhancements/oc/top-pvc-usage.md
Labels: lgtm, approved, jira/valid-reference

#1713 METAL-1045: baremetal:additional-ntp-servers
  enhancements/baremetal/additional-ntp-servers.md
Labels: lgtm, approved, jira/valid-reference

#1628 CM-235: Support for istio-csr through integration with cert-manager-operator
  enhancements/cert-manager/istio-csr-controller.md
  enhancements/cert-manager/istio-csr-create.png
  enhancements/cert-manager/istio-csr-create.puml
  enhancements/cert-manager/istio-csr-delete.png
  enhancements/cert-manager/istio-csr-delete.puml
Labels: lgtm, approved, jira/valid-reference

#1722 NO-JIRA: enhancements/update/OWNERS: Update owners
  enhancements/update/OWNERS
Labels: lgtm, approved, jira/valid-reference
