Repository openshift/enhancements, pull requests merged in 2024-12, with the labels that each got.

#1492 OTA-1029: Add a CVO Log Level API
  enhancements/update/cvo-log-level-api.md
Labels: lgtm, approved, jira/valid-reference

#1637 Split RHCOS into layers
  enhancements/rhcos/split-rhcos-into-layers.md
Labels: lgtm, approved

#1705 Add single team clause so feature gates align with enhancement guidance
  dev-guide/featuresets.md
Labels: lgtm, approved, lifecycle/stale

#1674 OCPEDGE-1191: feat: initial arbiter cluster enhancement
  enhancements/arbiter-clusters.md
Labels: lgtm, approved, tide/merge-method-squash, jira/valid-reference

#1723 USHIFT-4931: TLS cipher configuration options
  enhancements/microshift/microshift-tls-cipher.md
Labels: lgtm, approved, jira/valid-reference

#1725 SDN-5425: Explicitly configure address management with UDNs
  enhancements/network/user-defined-network-segmentation.md
Labels: lgtm, approved, jira/valid-reference

#1717 STOR-1306: Update LSO enhancement for symlink cleanup
  enhancements/storage/cleanup-lso-symlink.md
Labels: lgtm, approved, jira/valid-reference

#1714 OAPE-25: Customizing control plane machine names
  enhancements/machine-api/control-plane-machine-set.md
Labels: lgtm, approved, jira/valid-reference

#1712 IBMCloud post cluster creation service endpoint override support
  enhancements/cloud-integration/ibm/service-endpoint-dynamic-override.md
Labels: lgtm, approved
