Repository openshift/enhancements, pull requests merged in 2024-04, with the labels that each got.

#1548 USHIFT-2089: Add router configuration options
  enhancements/microshift/microshift-router-configuration.md
Labels: lgtm, approved, jira/valid-reference

#1604 this-week: 2024-04-05
  hack/this-week.sh
  this-week/2024-04-05.md
Labels: lgtm, approved

#1585 SDN-4433: Configurable network diagnostics pod placement
  enhancements/network/configurable-network-diagnostics-pod-placement.md
Labels: lgtm, approved, jira/valid-reference

#1607 this-week: 2024-04-12
  this-week/2024-04-12.md
Labels: lgtm, approved

#1522 OTA-916: enhancements/update/configurable-clusterversion-signature-stores: Tech-preview first
  enhancements/update/configurable-clusterversion-signature-stores.md
Labels: lgtm, approved, jira/valid-reference

#1601 OCPEDGE-919: MicroShift: Replacing upstream TopoLVM with a minified version of LVMS
  enhancements/microshift/lvms-topolvm-downstream-replacement.md
Labels: lgtm, approved, jira/valid-reference

#1415 NE-1129: Make ingress operator optional on HyperShift
  enhancements/ingress/optional-ingress-hypershift.md
Labels: lgtm, approved, jira/valid-reference

#1440 OPNET-268: Configure-ovs Alternative
  enhancements/network/configure-ovs-alternative.md
Labels: lgtm, approved, jira/valid-reference

#1609 this-week: 2024-04-19
  this-week/2024-04-19.md
Labels: lgtm, approved

#1267 vSphere IPI Support for Static IPs
  enhancements/network/static-ip-addresses-vsphere.md
Labels: lgtm, approved

#1608 add link to doc about declaring a feature Accessible-by-default
  dev-guide/api-conventions.md
Labels: lgtm, approved

#1610 OCPBUGS-28637: Update cluster-wide proxy Risks and Mitigations for Windows nodes.
  enhancements/windows-containers/windows-node-egress-proxy.md
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#1615 this-week: 2024-04-26
  this-week/2024-04-26.md
Labels: lgtm, approved
