Repository openshift/enhancements, pull requests merged in 2025-05, with the labels that each got.

#1790 NO-ISSUE: CONVENTIONS: Explain no plan for node-role.kubernetes.io/control-plane taint
  CONVENTIONS.md
Labels: lgtm, approved, jira/valid-reference

#1789 NO-JIRA: authentication: add external OIDC GA promotion plan details
  enhancements/authentication/direct-external-oidc-provider.md
Labels: lgtm, approved, jira/valid-reference

#1676 OpenShift Tests Extension Framework Initial
  enhancements/testing/openshift-tests-extension.md
Labels: lgtm, approved

#1782 USHIFT-5072: MicroShift router logging options
  enhancements/microshift/microshift-router-configuration-errors-logging.md
Labels: lgtm, approved, jira/valid-reference

#1677 SPLAT-1733: Update vSphere and include host/vm group
  enhancements/installer/vsphere-ipi-zonal.md
Labels: lgtm, approved, lifecycle/rotten, jira/valid-reference

#1748 STOR-2141: add enhancement for vSphere configurable max number of volumes per node
  enhancements/storage/vsphere-configurable-maximum-allowed-number-of-block-volumes-per-node.md
Labels: lgtm, approved, lifecycle/rotten, jira/valid-reference

#1778 ESO-82: Proposal to add external secrets operator for Red Hat OpenShift
  enhancements/external-secrets-operator/external-secrets-operator.md
Labels: lgtm, approved, jira/valid-reference
