Repository openshift/enhancements, pull requests merged in 2025-01, with the labels that each got.

#1716 enhancements/monitoring: add proposal for early-monitoring-config-validation
  enhancements/monitoring/early-monitoring-config-validation.md
Labels: lgtm, approved, lifecycle/rotten

#1735 NO-JIRA: Update references between CAPI enhancements
  enhancements/cluster-api/installing-cluster-api-components-in-ocp.md
  enhancements/machine-api/cluster-api-integration.md
  enhancements/machine-api/converting-machine-api-to-cluster-api.md
Labels: lgtm, approved, jira/valid-reference

#1727 split-rhcos-into-layers: tweak versioning scheme section
  enhancements/rhcos/split-rhcos-into-layers.md
Labels: lgtm, approved

#1733 SPLAT-1159: installer: support AWS Wavelength zones
  enhancements/installer/aws-custom-edge-local-wavelength-zones-diagram.png
  enhancements/installer/aws-custom-edge-machineset-wavelength-zones.md
Labels: lgtm, approved, jira/valid-reference

#1739 OCPBUGS-48740: Add missing CSP directives
  enhancements/console/dynamic-plugins.md
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#1446 NE-1366: Revisions for set-delete-http-headers EP
  enhancements/ingress/set-delete-http-headers.md
Labels: lgtm, approved, lifecycle/rotten, jira/valid-reference

#1593 NE-1517: Set EIP for NLB Ingress controller.
  enhancements/ingress/set_eip_nlb_ingress.md
Labels: lgtm, approved, lifecycle/rotten, jira/valid-reference

#1744 OCPBUGS-48740: Remove unnecessary object-src directive
  enhancements/console/dynamic-plugins.md
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#1726 (oidc): add considerations for impacted kube-apiserver admission plugins
  enhancements/authentication/direct-external-oidc-provider.md
Labels: lgtm, approved

#1634 CORS-3440: IngressController subnet selection at installation
  enhancements/installer/aws-lb-subnet-selection.md
Labels: lgtm, approved, jira/valid-reference
