Repository openshift/enhancements, pull requests merged in 2025-03, with the labels that each got.

#1728 OPNET-629: Add second HAProxy healthcheck port
  dev-guide/host-port-registry.md
Labels: lgtm, approved, jira/valid-reference

#1762 LOG-6768: Enable GCP WIF short-lived token support
  enhancements/cluster-logging/gcp-external-account-auth.md
Labels: lgtm, approved, jira/valid-reference

#1738 NO-JIRA: fix filename in featuresets docs
  dev-guide/featuresets.md
Labels: lgtm, approved, jira/valid-reference

#1741 NE-1112: Add Security Policy for Gateway API
  enhancements/ingress/gateway-api-with-cluster-ingress-operator.md
Labels: lgtm, approved, jira/valid-reference

#1770 Update feature promotion guidelines with details on automated vs manual testing
  dev-guide/featuresets.md
Labels: lgtm, approved

#1771 NE-1911: Revise the Security Policy for Gateway API
  enhancements/ingress/gateway-api-with-cluster-ingress-operator.md
Labels: lgtm, approved, tide/merge-method-rebase, jira/valid-reference
